/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { BaseResource } from '../../internal/base/index.js';
import { type ErrorResponse, type Response } from '../../internal/index.js';
import { type ISimulationTypeResponse } from '../../types/index.js';
import { SimulationType } from '../../entities/index.js';

const SimulationTypesPaths = {
  list: '/simulation-types',
} as const;

export class SimulationTypesResource extends BaseResource {
  public async list(): Promise<SimulationType[]> {
    const response = await this.client.get<undefined, Response<ISimulationTypeResponse[]> | ErrorResponse>(
      SimulationTypesPaths.list,
    );

    const data = this.handleResponse<ISimulationTypeResponse[]>(response);

    return data.map((simulationType) => new SimulationType(simulationType));
  }
}
