/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IAdjustmentTotalsBreakdown } from './adjustment-totals-breakdown.js';
import { type CurrencyCode } from '../../enums/index.js';

export interface IAdjustmentTotalsResponse {
  subtotal: string;
  tax: string;
  total: string;
  fee: string;
  earnings: string;
  breakdown?: IAdjustmentTotalsBreakdown | null;
  currency_code: CurrencyCode;
}
