/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITransactionsTimePeriodResponse } from '../index';

export interface ITransactionProrationResponse {
  rate: string;
  billing_period?: ITransactionsTimePeriodResponse | null;
}
