/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IAdjustmentsTimePeriodResponse } from './adjustments-time-period-response.js';

export interface IAdjustmentsProrationResponse {
  rate: string;
  billing_period?: IAdjustmentsTimePeriodResponse | null;
}
