/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CheckoutDomainApprovalStatus } from '../../../enums/index.js';

export interface ListCheckoutDomainsQueryParameters {
  after?: string;
  orderBy?: string;
  perPage?: number;
  domain?: string;
  status?: CheckoutDomainApprovalStatus[];
}
