/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CatalogType, type Status, type TaxMode } from '../../../enums/index.js';
import {
  type ICustomData,
  type IMoney,
  type IPriceQuantity,
  type ITimePeriod,
  type ITrialPeriod,
  type IUnitPriceOverride,
} from '../../../types/index.js';

export interface UpdatePriceRequestBody {
  description?: string;
  name?: string | null;
  type?: CatalogType | null;
  billingCycle?: ITimePeriod | null;
  trialPeriod?: ITrialPeriod | null;
  taxMode?: TaxMode;
  unitPrice?: IMoney;
  unitPriceOverrides?: IUnitPriceOverride[];
  quantity?: IPriceQuantity;
  status?: Status;
  customData?: ICustomData | null;
}
