/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type AdjustmentAction, type AdjustmentStatus } from '../../../enums';

export interface ListAdjustmentQueryParameters {
  action?: AdjustmentAction;
  after?: string;
  customerId?: string[];
  orderBy?: string;
  perPage?: number;
  status?: AdjustmentStatus[];
  subscriptionId?: string[];
  transactionId?: string[];
  id?: string[];
}
