/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import {
  type IProductNotificationResponse,
  type ISubscriptionPriceNotificationResponse,
  type ISubscriptionTimePeriodNotificationResponse,
} from '../index';
import { type SubscriptionItemStatus } from '../../../enums';

export interface ISubscriptionItemNotificationResponse {
  status: SubscriptionItemStatus;
  quantity: number;
  recurring: boolean;
  created_at: string;
  updated_at: string;
  previously_billed_at?: string | null;
  next_billed_at?: string | null;
  trial_dates?: ISubscriptionTimePeriodNotificationResponse | null;
  price?: ISubscriptionPriceNotificationResponse | null;
  product?: IProductNotificationResponse | null;
}
