/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IProductResponse } from '../../types';
import { Collection } from '../../internal/base';
import { Product } from './product';

export class ProductCollection extends Collection<IProductResponse, Product> {
  override fromJson(data: IProductResponse): Product {
    return new Product(data);
  }
}
