/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IAdjustmentOriginalAmountNotificationResponse } from '../index';

export interface IChargebackFeeNotification {
  amount: string;
  original?: IAdjustmentOriginalAmountNotificationResponse | null;
}
