/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IPaymentCardNotificationResponse } from '../index';
import { type PaymentType } from '../../../enums';

export interface IPaymentMethodDetailsNotification {
  type: PaymentType;
  card?: IPaymentCardNotificationResponse | null;
}
