/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */
import { IKoreanMarketUnderlyingDetailsNotification } from './korean-market-underlying-details-notification.js';

export interface IPaymentMethodUnderlyingDetailsNotification {
  korea_local: IKoreanMarketUnderlyingDetailsNotification;
}
