/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITotalsNotification } from '../index';

export interface ITaxRatesUsedNotificationResponse {
  tax_rate: string;
  totals?: ITotalsNotification | null;
}
