/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type Interval } from '../../../enums/index.js';

export interface ITimePeriodNotification {
  interval: Interval;
  frequency: number;
}
