/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CurrencyCode } from '../../../enums/index.js';

export interface ITotalAdjustmentsNotificationResponse {
  subtotal: string;
  tax: string;
  total: string;
  fee: string;
  earnings: string;
  currency_code: CurrencyCode;
}
