/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CurrencyCode } from '../../../enums/index.js';

export interface ITransactionTotalsAdjustedNotificationResponse {
  subtotal: string;
  tax: string;
  total: string;
  grand_total: string;
  fee?: string | null;
  earnings?: string | null;
  currency_code: CurrencyCode;
}
