/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMoneyNotificationResponse } from '../index';
import { type CountryCode } from '../../../enums';

export interface IUnitPriceOverrideNotificationResponse {
  country_codes: CountryCode[];
  unit_price: IMoneyNotificationResponse;
}
