/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export interface ReviseTransactionRequestBody {
  customer?: {
    name?: string;
  };
  business?: {
    name?: string;
    taxIdentifier?: string;
  };
  address?: {
    firstLine?: string;
    secondLine?: string | null;
    city?: string;
    region?: string;
  };
}
