/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ISubscriptionTimePeriodNotificationResponse } from '../../types/index.js';

export class SubscriptionTimePeriodNotification {
  public readonly startsAt: string;
  public readonly endsAt: string;

  constructor(subscriptionTimePeriod: ISubscriptionTimePeriodNotificationResponse) {
    this.startsAt = subscriptionTimePeriod.starts_at;
    this.endsAt = subscriptionTimePeriod.ends_at;
  }
}
