/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ISubscriptionScheduledChangeNotificationResponse } from '../../types';
import { type ScheduledChangeAction } from '../../../enums';

export class SubscriptionScheduledChangeNotification {
  public readonly action: ScheduledChangeAction;
  public readonly effectiveAt: string;
  public readonly resumeAt: string | null;

  constructor(subscriptionScheduledChange: ISubscriptionScheduledChangeNotificationResponse) {
    this.action = subscriptionScheduledChange.action;
    this.effectiveAt = subscriptionScheduledChange.effective_at;
    this.resumeAt = subscriptionScheduledChange.resume_at ? subscriptionScheduledChange.resume_at : null;
  }
}
