/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ActionSource, type SubscriptionHistoryReason } from '../../enums/index.js';
import { type ISubscriptionHistoryResponse } from '../../types/index.js';
import { SubscriptionHistoryActor } from './subscription-history-actor.js';
import { hydrateSubscriptionHistoryDetail, type SubscriptionHistoryDetail } from './subscription-history-detail.js';

export class SubscriptionHistory {
  public readonly id: string;
  public readonly groupId: string;
  public readonly subscriptionId: string;
  public readonly occurredAt: string;
  public readonly source: ActionSource;
  public readonly actor: SubscriptionHistoryActor;
  public readonly reason: SubscriptionHistoryReason | null;
  public readonly detail: SubscriptionHistoryDetail;

  constructor(subscriptionHistory: ISubscriptionHistoryResponse) {
    this.id = subscriptionHistory.id;
    this.groupId = subscriptionHistory.group_id;
    this.subscriptionId = subscriptionHistory.subscription_id;
    this.occurredAt = subscriptionHistory.occurred_at;
    this.source = subscriptionHistory.source;
    this.actor = new SubscriptionHistoryActor(subscriptionHistory.actor);
    this.reason = subscriptionHistory.reason;
    this.detail = hydrateSubscriptionHistoryDetail(subscriptionHistory.detail);
  }
}
