/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event';
import { SubscriptionCreatedNotification } from '../../entities';
import { EventName } from '../../helpers';
import { type IEventsResponse } from '../../../types';
import { type ISubscriptionCreatedNotificationResponse } from '../../types';

export class SubscriptionCreatedEvent extends Event {
  public override readonly eventType = EventName.SubscriptionCreated;
  public override readonly data: SubscriptionCreatedNotification;

  constructor(response: IEventsResponse<ISubscriptionCreatedNotificationResponse>) {
    super(response);
    this.data = new SubscriptionCreatedNotification(response.data);
  }
}
