/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import type { SimulationScenarioType, SimulationStatus } from '../../enums/index.js';
import type { IEventName } from '../../notifications/index.js';

export interface ISimulationResponse {
  id: string;
  status: SimulationStatus;
  notification_setting_id: string;
  name: string;
  type: IEventName | SimulationScenarioType;
  payload?: any;
  last_run_at?: string | null;
  created_at: string;
  updated_at: string;
}
