/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import type { SimulationEventType, Status } from '../../enums';
import type { IEventName, EventMap } from '../../notifications';

export interface ISimulationResponse<T extends SimulationEventType | undefined = undefined> {
  id: string;
  status: Status;
  notification_setting_id: string;
  name: string;
  type: T;
  payload?: (T extends IEventName ? EventMap[T] : null) | null;
  last_run_at?: string | null;
  created_at: string;
  updated_at: string;
}
