/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ActionSource, type SubscriptionHistoryReason } from '../../enums/index.js';
import { type ISubscriptionHistoryActorResponse } from './subscription-history-actor-response.js';
import { type ISubscriptionHistoryDetailResponse } from './subscription-history-detail-response.js';

export interface ISubscriptionHistoryResponse {
  id: string;
  group_id: string;
  subscription_id: string;
  occurred_at: string;
  source: ActionSource;
  actor: ISubscriptionHistoryActorResponse;
  reason: SubscriptionHistoryReason | null;
  detail: ISubscriptionHistoryDetailResponse;
}
