/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import {
  type SubscriptionConsentRequirementStatus,
  type SubscriptionConsentRequirementType,
} from '../../enums/index.js';
import { type ISubscriptionTimePeriodResponse } from '../subscription/index.js';

export interface ISubscriptionHistoryConsentRequirementResponse {
  id: string;
  requirement: SubscriptionConsentRequirementType;
  status: SubscriptionConsentRequirementStatus;
  created_at: string;
  consent_period: ISubscriptionTimePeriodResponse | null;
  granted_at: string | null;
  voided_at: string | null;
}
