version: 2
updates:
  - package-ecosystem: npm
    directory: /
    labels:
      - dependencies
      - javascript
      - norelease
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    groups:
      npm:
        patterns:
          - "*"
