/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */
import type { Status } from '../../../enums/index.js';

export interface UpdateDiscountGroupRequestBody {
  status?: Status;
  name?: string;
}
