/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ICustomerPortalSubscriptionUrl } from '../../types/index.js';

export class CustomerPortalSubscriptionUrl {
  public readonly id: string;
  public readonly cancelSubscription: string;
  public readonly updateSubscriptionPaymentMethod: string;

  constructor(customerPortalSubscriptionUrlResponse: ICustomerPortalSubscriptionUrl) {
    this.id = customerPortalSubscriptionUrlResponse.id;
    this.cancelSubscription = customerPortalSubscriptionUrlResponse.cancel_subscription;
    this.updateSubscriptionPaymentMethod = customerPortalSubscriptionUrlResponse.update_subscription_payment_method;
  }
}
