/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IGeneralResponse } from '../../types/index.js';

export class General {
  public readonly overview: string;

  constructor(generalResponse: IGeneralResponse) {
    this.overview = generalResponse.overview;
  }
}
