env:
  browser: true
  es2021: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  '@typescript-eslint/semi': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'
  '@typescript-eslint/ban-types': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/restrict-template-expressions': 'off'
  '@typescript-eslint/comma-dangle': 'off'
  '@typescript-eslint/space-before-function-paren': 'off'
  '@typescript-eslint/member-delimiter-style': 'off'
  '@typescript-eslint/indent': 'off'
  'generator-star-spacing': 'off'
  '@typescript-eslint/naming-convention': 'off'
  '@typescript-eslint/no-extraneous-class': 'off'
ignorePatterns:
  - 'jest.config.js'
  - '**/__tests__/**'
