/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMoneyResponse } from '../shared/index.js';
import { type ISubscriptionResultResponse } from './subscription-result-response.js';

export interface ISubscriptionPreviewUpdateSummary {
  credit: IMoneyResponse;
  charge: IMoneyResponse;
  result: ISubscriptionResultResponse;
}
