/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import {
  type ISubscriptionDiscountResponse,
  type IBillingDetailsResponse,
  type ITimePeriod,
  type ISubscriptionScheduledChangeResponse,
  type ISubscriptionItemResponse,
  type ICustomData,
  type INextTransactionResponse,
  type ITransactionDetailsPreviewResponse,
  type ISubscriptionTimePeriodResponse,
  type ISubscriptionManagementResponse,
  type ISubscriptionPreviewUpdateSummary,
  type IImportMetaResponse,
} from '../index';
import { type CurrencyCode, type CollectionMode, type SubscriptionStatus } from '../../enums';

export interface ISubscriptionPreviewResponse {
  status: SubscriptionStatus;
  customer_id: string;
  address_id: string;
  business_id?: string | null;
  currency_code: CurrencyCode;
  created_at: string;
  updated_at: string;
  started_at?: string | null;
  first_billed_at?: string | null;
  next_billed_at?: string | null;
  paused_at?: string | null;
  canceled_at?: string | null;
  discount?: ISubscriptionDiscountResponse | null;
  collection_mode: CollectionMode;
  billing_details?: IBillingDetailsResponse | null;
  current_billing_period?: ISubscriptionTimePeriodResponse | null;
  billing_cycle?: ITimePeriod | null;
  scheduled_change?: ISubscriptionScheduledChangeResponse | null;
  management_urls?: ISubscriptionManagementResponse | null;
  items: ISubscriptionItemResponse[];
  custom_data?: ICustomData | null;
  immediate_transaction?: INextTransactionResponse | null;
  next_transaction?: INextTransactionResponse | null;
  recurring_transaction_details?: ITransactionDetailsPreviewResponse | null;
  update_summary?: ISubscriptionPreviewUpdateSummary | null;
  import_meta?: IImportMetaResponse | null;
}
