/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type ReportType =
  | 'adjustments'
  | 'adjustment_line_items'
  | 'transactions'
  | 'transaction_line_items'
  | 'discounts'
  | 'products_prices'
  /**
   * @deprecated 'balance' is deprecated. Use 'payout_reconciliation' instead.
   */
  | 'balance'
  | 'payout_reconciliation';
