/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Address } from './address';
import { type IAddressResponse } from '../../types';
import { Collection } from '../../internal/base';

export class AddressCollection extends Collection<IAddressResponse, Address> {
  override fromJson(data: IAddressResponse): Address {
    return new Address(data);
  }
}
