/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Simulation, SimulationCollection } from '../../entities';
import { type ErrorResponse, type Response } from '../../internal';
import { BaseResource, PathParameters, QueryParameters } from '../../internal/base';
import { type ISimulationResponse } from '../../types';
import {
  type CreateSimulationRequestBody,
  type ListSimulationQueryParameters,
  type UpdateSimulationRequestBody,
} from './operations';

export * from './operations';

const SimulationPaths = {
  list: '/simulations',
  create: '/simulations',
  get: '/simulations/{simulation_id}',
  update: '/simulations/{simulation_id}',
} as const;

export class SimulationsResource extends BaseResource {
  public list(queryParams?: ListSimulationQueryParameters): SimulationCollection {
    const queryParameters = new QueryParameters(queryParams);
    return new SimulationCollection(this.client, SimulationPaths.list + queryParameters.toQueryString());
  }

  public async create(createSimulationParameters: CreateSimulationRequestBody): Promise<Simulation> {
    const response = await this.client.post<CreateSimulationRequestBody, Response<ISimulationResponse> | ErrorResponse>(
      SimulationPaths.create,
      createSimulationParameters,
    );

    const data = this.handleResponse<ISimulationResponse>(response);

    return new Simulation(data);
  }

  public async get(simulationId: string): Promise<Simulation> {
    const urlWithPathParams = new PathParameters(SimulationPaths.get, {
      simulation_id: simulationId,
    }).deriveUrl();

    const response = await this.client.get<undefined, Response<ISimulationResponse> | ErrorResponse>(urlWithPathParams);

    const data = this.handleResponse<ISimulationResponse>(response);

    return new Simulation(data);
  }

  public async update(simulationId: string, updateSimulation: UpdateSimulationRequestBody): Promise<Simulation> {
    const urlWithPathParams = new PathParameters(SimulationPaths.update, {
      simulation_id: simulationId,
    }).deriveUrl();

    const response = await this.client.patch<
      UpdateSimulationRequestBody,
      Response<ISimulationResponse> | ErrorResponse
    >(urlWithPathParams, updateSimulation);

    const data = this.handleResponse<ISimulationResponse>(response);

    return new Simulation(data);
  }
}
