/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ICustomData } from '../../../types';
import { type TaxCategory, type Status, type CatalogType } from '../../../enums';

export interface UpdateProductRequestBody {
  name?: string;
  description?: string | null;
  type?: CatalogType | null;
  taxCategory?: TaxCategory;
  imageUrl?: string | null;
  customData?: ICustomData | null;
  status?: Status;
}
