/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Simulation } from '../../entities';
import { type ISimulationResponse } from '../../types';
import { Collection } from '../../internal/base';
import type { IEventName } from '../../notifications';
import type { SimulationScenarioType } from '../../enums';

export class SimulationCollection<T extends IEventName | SimulationScenarioType> extends Collection<
  ISimulationResponse<T>,
  Simulation<T>
> {
  override fromJson(data: ISimulationResponse<T>): Simulation<T> {
    return new Simulation(data);
  }
}
