/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Simulation } from '../../entities/index.js';
import { type ISimulationResponse } from '../../types/index.js';
import { Collection } from '../../internal/base/index.js';

export class SimulationCollection extends Collection<ISimulationResponse, Simulation> {
  override fromJson(data: ISimulationResponse): Simulation {
    return new Simulation(data);
  }
}
