/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export interface ListSimulationRunQueryParameters {
  after?: string;
  include?: any[];
  orderBy?: string;
  perPage?: number;
  id?: string[];
}
