/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CatalogType, type Status, type TaxCategory } from '../../../enums/index.js';
import { type ICustomData } from '../../../types/index.js';
import { type IImportMetaNotificationResponse, type ISharedPriceNotificationResponse } from '../shared/index.js';

export interface IProductNotificationResponse {
  id: string;
  name: string;
  type?: CatalogType | null;
  description?: string | null;
  tax_category: TaxCategory;
  image_url?: string | null;
  custom_data?: ICustomData | null;
  status: Status;
  created_at: string;
  import_meta?: IImportMetaNotificationResponse | null;
  prices?: ISharedPriceNotificationResponse[] | null;
}
