/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CurrencyCode, type PayoutStatus } from '../../../enums/index.js';

export interface IPayoutNotificationResponse {
  id: string;
  status: PayoutStatus;
  amount: string;
  currency_code: CurrencyCode;
}
