/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type Status } from '../../enums/index.js';
import { type ICustomData, type IImportMetaResponse } from '../shared/index.js';

export interface ICustomerResponse {
  id: string;
  name?: string | null;
  email: string;
  marketing_consent: boolean;
  status: Status;
  custom_data?: ICustomData | null;
  locale: string;
  created_at: string;
  updated_at: string;
  import_meta?: IImportMetaResponse | null;
}
