/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Adjustment } from './adjustment';
import { type IAdjustmentResponse } from '../../types';
import { Collection } from '../../internal/base';

export class AdjustmentCollection extends Collection<IAdjustmentResponse, Adjustment> {
  override fromJson(data: IAdjustmentResponse): Adjustment {
    return new Adjustment(data);
  }
}
