/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */
import { Event } from '../../../entities/events/event';
import { DiscountNotification } from '../../entities';
import { type IEventsResponse } from '../../../types';
import { EventName } from '../../helpers';
import { type IDiscountNotificationResponse } from '../../types';

export class DiscountImportedEvent extends Event {
  public override readonly eventType = EventName.DiscountImported;
  public override readonly data: DiscountNotification;

  constructor(response: IEventsResponse<IDiscountNotificationResponse>) {
    super(response);
    this.data = new DiscountNotification(response.data);
  }
}
