/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { BaseResource } from '../../internal/base/index.js';
import { EventType } from '../../entities/index.js';
import { type IEventTypeResponse } from '../../types/index.js';
import { type Response, type ErrorResponse } from '../../internal/index.js';

const EventTypesPaths = {
  list: '/event-types',
} as const;

export class EventTypesResource extends BaseResource {
  public async list(): Promise<EventType[]> {
    const response = await this.client.get<undefined, Response<IEventTypeResponse[]> | ErrorResponse>(
      EventTypesPaths.list,
    );

    const data = this.handleResponse<IEventTypeResponse[]>(response);

    return data.map((eventType) => new EventType(eventType));
  }
}
