/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IPriceResponse } from '../../types';
import { Collection } from '../../internal/base';
import { Price } from './price';

export class PriceCollection extends Collection<IPriceResponse, Price> {
  override fromJson(data: IPriceResponse): Price {
    return new Price(data);
  }
}
