/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type Status } from '../../../enums/index.js';
import { type CustomData } from '../../../entities/index.js';
import { ImportMetaNotification } from '../shared/index.js';
import { type ICustomerNotificationResponse } from '../../types/index.js';

export class CustomerNotification {
  public readonly id: string;
  public readonly name: string | null;
  public readonly email: string;
  public readonly marketingConsent: boolean;
  public readonly status: Status;
  public readonly customData: CustomData | null;
  public readonly locale: string;
  public readonly createdAt: string;
  public readonly updatedAt: string;
  public readonly importMeta: ImportMetaNotification | null;

  constructor(customer: ICustomerNotificationResponse) {
    this.id = customer.id;
    this.name = customer.name ? customer.name : null;
    this.email = customer.email;
    this.marketingConsent = customer.marketing_consent;
    this.status = customer.status;
    this.customData = customer.custom_data ? customer.custom_data : null;
    this.locale = customer.locale;
    this.createdAt = customer.created_at;
    this.updatedAt = customer.updated_at;
    this.importMeta = customer.import_meta ? new ImportMetaNotification(customer.import_meta) : null;
  }
}
