/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event';
import { ReportNotification } from '../../entities';
import { EventName } from '../../helpers';
import { type IEventsResponse } from '../../../types';
import { type IReportNotificationResponse } from '../../types';

export class ReportCreatedEvent extends Event {
  public override readonly eventType = EventName.ReportCreated;
  public override readonly data: ReportNotification;

  constructor(response: IEventsResponse<IReportNotificationResponse>) {
    super(response);
    this.data = new ReportNotification(response.data);
  }
}
