/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type SavedPaymentMethodType = 'alipay' | 'apple_pay' | 'card' | 'google_pay' | 'korea_local' | 'paypal';
