/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IChargebackFee } from '../../types';
import { AdjustmentOriginalAmount } from '../index';

export class ChargebackFee {
  public readonly amount: string;
  public readonly original: AdjustmentOriginalAmount | null;

  constructor(chargebackFee: IChargebackFee) {
    this.amount = chargebackFee.amount;
    this.original = chargebackFee.original ? new AdjustmentOriginalAmount(chargebackFee.original) : null;
  }
}
