/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type PaymentType } from '../../enums/index.js';
import { PaymentCard } from './payment-card.js';
import { type IPaymentMethodDetails } from '../../types/index.js';

export class PaymentMethodDetails {
  public readonly type: PaymentType;
  public readonly card: PaymentCard | null;

  constructor(paymentMethodDetails: IPaymentMethodDetails) {
    this.type = paymentMethodDetails.type;
    this.card = paymentMethodDetails.card ? new PaymentCard(paymentMethodDetails.card) : null;
  }
}
