/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { IPaymentMethodUnderlyingDetails } from '../../types/index.js';
import { KoreanMarketUnderlyingDetails } from './korean-market-underlying-details.js';

export class PaymentMethodUnderlyingDetails {
  public readonly koreaLocal: KoreanMarketUnderlyingDetails | null;

  constructor(paymentMethodUnderlyingDetails: IPaymentMethodUnderlyingDetails) {
    this.koreaLocal = paymentMethodUnderlyingDetails.korea_local
      ? new KoreanMarketUnderlyingDetails(paymentMethodUnderlyingDetails.korea_local)
      : null;
  }
}
