/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IPaymentCardResponse } from '../../types';
import { type PaymentCardType } from '../../enums';

export class PaymentCard {
  public readonly type: PaymentCardType;
  public readonly last4: string;
  public readonly expiryMonth: number;
  public readonly expiryYear: number;
  public readonly cardholderName: string;

  constructor(paymentCard: IPaymentCardResponse) {
    this.type = paymentCard.type;
    this.last4 = paymentCard.last4;
    this.expiryMonth = paymentCard.expiry_month;
    this.expiryYear = paymentCard.expiry_year;
    this.cardholderName = paymentCard.cardholder_name;
  }
}
