/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ISimulationEventResponse } from '../../types/index.js';

export class SimulationEventResponse {
  public readonly body: string;
  public readonly statusCode: number;

  constructor(simulationEventResponse: ISimulationEventResponse) {
    this.body = simulationEventResponse.body;
    this.statusCode = simulationEventResponse.status_code;
  }
}
