/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITransactionPaymentAttemptResponse } from '../../types';
import { PaymentMethodDetails } from '../index';
import { type PaymentAttemptStatus, type ErrorCode } from '../../enums';

export class TransactionPaymentAttempt {
  public readonly paymentAttemptId: string;
  public readonly paymentMethodId: string | null;
  /**
   * @deprecated use paymentMethodId instead
   */
  public readonly storedPaymentMethodId: string;
  public readonly amount: string;
  public readonly status: PaymentAttemptStatus;
  public readonly errorCode: ErrorCode | null;
  public readonly methodDetails: PaymentMethodDetails | null;
  public readonly createdAt: string;
  public readonly capturedAt: string | null;

  constructor(transactionPaymentAttempt: ITransactionPaymentAttemptResponse) {
    this.paymentAttemptId = transactionPaymentAttempt.payment_attempt_id;
    this.paymentMethodId = transactionPaymentAttempt.payment_method_id ?? null;
    this.storedPaymentMethodId = transactionPaymentAttempt.stored_payment_method_id;
    this.amount = transactionPaymentAttempt.amount;
    this.status = transactionPaymentAttempt.status;
    this.errorCode = transactionPaymentAttempt.error_code ? transactionPaymentAttempt.error_code : null;
    this.methodDetails = transactionPaymentAttempt.method_details
      ? new PaymentMethodDetails(transactionPaymentAttempt.method_details)
      : null;
    this.createdAt = transactionPaymentAttempt.created_at;
    this.capturedAt = transactionPaymentAttempt.captured_at ? transactionPaymentAttempt.captured_at : null;
  }
}
