/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITransactionPayPalResponse } from '../../types/index.js';

export class TransactionPayPal {
  public readonly email: string;
  public readonly reference: string | null;

  constructor(transactionPayPalResponse: ITransactionPayPalResponse) {
    this.email = transactionPayPalResponse.email;
    this.reference = transactionPayPalResponse.reference;
  }
}
