/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CountryCode } from '../../enums/index.js';
import { Money } from './money.js';
import { type IUnitPriceOverrideResponse } from '../../types/index.js';

export class UnitPriceOverride {
  public readonly countryCodes: CountryCode[];
  public readonly unitPrice: Money;

  constructor(unitPriceOverride: IUnitPriceOverrideResponse) {
    this.countryCodes = unitPriceOverride.country_codes;
    this.unitPrice = new Money(unitPriceOverride.unit_price);
  }
}
