/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import {
  type IAdjustmentItemTotalsNotificationResponse,
  type IAdjustmentsProrationNotificationResponse,
} from '../index';
import { type AdjustmentType } from '../../../enums';

export interface IAdjustmentItemNotificationResponse {
  id: string;
  item_id: string;
  type: AdjustmentType;
  amount?: string | null;
  proration?: IAdjustmentsProrationNotificationResponse | null;
  totals?: IAdjustmentItemTotalsNotificationResponse | null;
}
