/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IAdjustmentsTimePeriodNotificationResponse } from '../index';

export interface IAdjustmentsProrationNotificationResponse {
  rate: string;
  billing_period?: IAdjustmentsTimePeriodNotificationResponse | null;
}
