/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IPayoutResponse } from '../../types';
import { type CurrencyCode, type PayoutStatus } from '../../enums';

export class Payout {
  public readonly id: string;
  public readonly status: PayoutStatus;
  public readonly amount: string;
  public readonly currencyCode: CurrencyCode;

  constructor(payout: IPayoutResponse) {
    this.id = payout.id;
    this.status = payout.status;
    this.amount = payout.amount;
    this.currencyCode = payout.currency_code;
  }
}
