/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CatalogType, type Status, type TaxCategory } from '../../enums/index.js';
import { type ICustomData, type IImportMetaResponse } from '../shared/index.js';
import { type IPriceResponse } from '../price/index.js';

export interface IProductResponse {
  id: string;
  name: string;
  type?: CatalogType | null;
  description?: string | null;
  tax_category: TaxCategory;
  image_url?: string | null;
  custom_data?: ICustomData | null;
  status: Status;
  created_at: string;
  updated_at: string;
  import_meta?: IImportMetaResponse | null;
  prices?: IPriceResponse[] | null;
}
