/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IEventName } from '../../../notifications/index.js';
import { type NotificationSettingsType } from '../../../enums/index.js';

export interface CreateNotificationSettingsRequestBody {
  description: string;
  destination: string;
  subscribedEvents: IEventName[];
  type: NotificationSettingsType;
  apiVersion?: number | null;
  includeSensitiveFields?: boolean | null;
}
