/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type TrafficSource } from '../../../enums/index.js';
import { type IEventName } from '../../../notifications/index.js';

export interface UpdateNotificationSettingsRequestBody {
  description?: string;
  destination?: string;
  active?: boolean;
  apiVersion?: number;
  includeSensitiveFields?: boolean;
  subscribedEvents?: IEventName[];
  trafficSource?: TrafficSource;
}
