/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */
import { type IEventTypeResponse } from '../../types';
import { type IEventName } from '../../notifications';

export class EventType {
  public readonly name: IEventName;
  public readonly description: string;
  public readonly group: string;
  public readonly availableVersions: number[];

  constructor(eventType: IEventTypeResponse) {
    this.name = eventType.name;
    this.description = eventType.description;
    this.group = eventType.group;
    this.availableVersions = eventType.available_versions;
  }
}
