/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type Status } from '../../../enums/index.js';
import { ContactsNotification } from './contacts-notification.js';
import { type CustomData } from '../../../entities/index.js';
import { ImportMetaNotification } from '../shared/index.js';
import { type IBusinessNotificationResponse } from '../../types/index.js';

export class BusinessNotification {
  public readonly id: string;
  public readonly customerId: string | null;
  public readonly name: string;
  public readonly companyNumber: string | null;
  public readonly taxIdentifier: string | null;
  public readonly status: Status;
  public readonly contacts: ContactsNotification[] | null;
  public readonly createdAt: string;
  public readonly updatedAt: string;
  public readonly customData: CustomData | null;
  public readonly importMeta: ImportMetaNotification | null;

  constructor(business: IBusinessNotificationResponse) {
    this.id = business.id;
    this.customerId = business.customer_id ?? null;
    this.name = business.name;
    this.companyNumber = business.company_number ? business.company_number : null;
    this.taxIdentifier = business.tax_identifier ? business.tax_identifier : null;
    this.status = business.status;
    this.contacts = business.contacts ? business.contacts.map((contact) => new ContactsNotification(contact)) : null;
    this.createdAt = business.created_at;
    this.updatedAt = business.updated_at;
    this.customData = business.custom_data ? business.custom_data : null;
    this.importMeta = business.import_meta ? new ImportMetaNotification(business.import_meta) : null;
  }
}
