/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event';
import { Business } from '../../../entities';
import { type IBusinessResponse, type IEventsResponse } from '../../../types';
import { EventName } from '../../helpers';

export class BusinessUpdatedEvent extends Event {
  public override readonly eventType = EventName.BusinessUpdated;
  public override readonly data: Business;

  constructor(response: IEventsResponse<IBusinessResponse>) {
    super(response);
    this.data = new Business(response.data);
  }
}
