/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IUsageEventErrorFieldResponse } from '../../types/index.js';

export class UsageEventErrorField {
  public readonly field: string;
  public readonly message: string;

  constructor(errorField: IUsageEventErrorFieldResponse) {
    this.field = errorField.field;
    this.message = errorField.message;
  }
}
