/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { SimulationRun } from '../../entities/index.js';
import { type ISimulationRunResponse } from '../../types/index.js';
import { Collection } from '../../internal/base/index.js';

export class SimulationRunCollection extends Collection<ISimulationRunResponse, SimulationRun> {
  override fromJson(data: ISimulationRunResponse): SimulationRun {
    return new SimulationRun(data);
  }
}
