/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import type { SimulationRunEventsStatus, SimulationScenarioType } from '../../enums/index.js';
import type { IEventName } from '../../notifications/index.js';
import { type ISimulationRunEvent } from '../../types/index.js';

export class SimulationRunEvent {
  public readonly id: string;
  public readonly status: SimulationRunEventsStatus;
  public readonly eventType: IEventName | SimulationScenarioType;
  public readonly payload: any;
  public readonly request: {
    body: string;
  } | null;

  public readonly response: {
    body: string;
    status_code: number;
  } | null;

  public readonly createdAt: string;
  public readonly updatedAt: string;

  constructor(simulationRunEventResponse: ISimulationRunEvent) {
    this.id = simulationRunEventResponse.id;
    this.status = simulationRunEventResponse.status;
    this.eventType = simulationRunEventResponse.event_type;
    this.payload = simulationRunEventResponse.payload;
    this.request = simulationRunEventResponse.request ?? null;
    this.response = simulationRunEventResponse.response ?? null;
    this.createdAt = simulationRunEventResponse.created_at;
    this.updatedAt = simulationRunEventResponse.updated_at;
  }
}
