/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import type { Status, SimulationScenarioType } from '../../enums/index.js';
import type { IEventName } from '../../notifications/index.js';

export interface ISimulationRunEvent {
  id: string;
  status: Status;
  event_type: IEventName | SimulationScenarioType;
  payload: any;
  request?: {
    body: string;
  } | null;
  response?: {
    body: string;
    status_code: number;
  } | null;
  created_at: string;
  updated_at: string;
}
