/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event';
import { Product } from '../../../entities';
import { EventName } from '../../helpers';
import { type IEventsResponse, type IProductResponse } from '../../../types';

export class ProductImportedEvent extends Event {
  public override readonly eventType = EventName.ProductImported;
  public override readonly data: Product;

  constructor(response: IEventsResponse<IProductResponse>) {
    super(response);
    this.data = new Product(response.data);
  }
}
