/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event.js';
import { EventName } from '../../helpers/index.js';
import { ProductNotification } from '../../entities/index.js';
import { type IEventsResponse } from '../../../types/index.js';
import { type IProductNotificationResponse } from '../../types/index.js';

export class ProductImportedEvent extends Event {
  public override readonly eventType = EventName.ProductImported;
  public override readonly data: ProductNotification;

  constructor(response: IEventsResponse<IProductNotificationResponse>) {
    super(response);
    this.data = new ProductNotification(response.data);
  }
}
