/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event.js';
import { EventName } from '../../helpers/index.js';
import { ClientTokenNotification } from '../../entities/index.js';
import { type IEventsResponse } from '../../../types/index.js';
import { IClientTokenNotificationResponse } from '../../types/index.js';

export class ClientTokenCreatedEvent extends Event {
  public override readonly eventType = EventName.ClientTokenCreated;
  public override readonly data: ClientTokenNotification;

  constructor(response: IEventsResponse<IClientTokenNotificationResponse>) {
    super(response);
    this.data = new ClientTokenNotification(response.data);
  }
}
