/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Collection } from '../../internal/base/index.js';
import { Report } from './report.js';
import { type IReportResponse } from '../../types/index.js';

export class ReportCollection extends Collection<IReportResponse, Report> {
  override fromJson(data: IReportResponse): Report {
    return new Report(data);
  }
}
