/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IReportResponse } from '../../types';
import { ReportFilters } from '../index';
import { type ReportStatus, type ReportType } from '../../enums';

export class Report {
  public readonly id: string;
  public readonly status: ReportStatus;
  public readonly rows: number | null;
  public readonly type: ReportType;
  public readonly filters: ReportFilters[];
  public readonly expiresAt: string | null;
  public readonly createdAt: string;

  constructor(reportResponse: IReportResponse) {
    this.id = reportResponse.id;
    this.status = reportResponse.status;
    this.rows = reportResponse.rows ?? null;
    this.type = reportResponse.type;
    this.filters = reportResponse.filters?.map((filter) => new ReportFilters(filter));
    this.expiresAt = reportResponse.expires_at ?? null;
    this.createdAt = reportResponse.created_at;
  }
}
