/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event';
import { AdjustmentNotification } from '../../entities';
import { type IEventsResponse } from '../../../types';
import { EventName } from '../../helpers';
import { type IAdjustmentNotificationResponse } from '../../types';

export class AdjustmentUpdatedEvent extends Event {
  public override readonly eventType = EventName.AdjustmentUpdated;
  public override readonly data: AdjustmentNotification;

  constructor(response: IEventsResponse<IAdjustmentNotificationResponse>) {
    super(response);
    this.data = new AdjustmentNotification(response.data);
  }
}
