/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event';
import { Adjustment } from '../../../entities';
import { type IAdjustmentResponse, type IEventsResponse } from '../../../types';
import { EventName } from '../../helpers';

export class AdjustmentUpdatedEvent extends Event {
  public override readonly eventType = EventName.AdjustmentUpdated;
  public override readonly data: Adjustment;

  constructor(response: IEventsResponse<IAdjustmentResponse>) {
    super(response);
    this.data = new Adjustment(response.data);
  }
}
