/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ReportFilterName, type ReportFilterOperator } from '../../../enums/index.js';
import { type IReportFiltersNotification } from '../../types/index.js';

export class ReportFiltersNotification {
  public readonly name: ReportFilterName;
  public readonly operator: null | ReportFilterOperator;
  public readonly value: string[] | string;

  constructor(reportFiltersResponse: IReportFiltersNotification) {
    this.name = reportFiltersResponse.name;
    this.operator = reportFiltersResponse.operator ?? null;
    this.value = reportFiltersResponse.value;
  }
}
