/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */
import { type ReportStatus } from '../../../enums';

export interface ListReportQueryParameters {
  after?: string;
  orderBy?: string;
  perPage?: number;
  status?: ReportStatus[];
}
