/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { ClientTokenStatus } from '../../../enums/index.js';

export interface ListClientTokenQueryParameters {
  after?: string;
  orderBy?: string;
  perPage?: number;
  status?: ClientTokenStatus[];
}
