/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ICustomData } from '../../../types';
import { type Status } from '../../../enums';

export interface UpdateCustomerRequestBody {
  name?: string | null;
  email?: string;
  status?: Status;
  customData?: ICustomData | null;
  locale?: string;
}
