/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type SubscriptionHistoryReason =
  | 'cardless_trial_ended'
  | 'import_issue'
  | 'missing_consent'
  | 'seller_request'
  | 'customer_request'
  | 'chargeback'
  | 'eu_withdrawal';
