/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type SubscriptionHistoryPaymentAttemptedOperation =
  | 'subscription_update'
  | 'subscription_one_off_charge'
  | 'subscription_activate';
