/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type ApiKeyPermission =
  | 'address.read'
  | 'address.write'
  | 'adjustment.read'
  | 'adjustment.write'
  | 'business.read'
  | 'business.write'
  | 'customer.read'
  | 'customer.write'
  | 'customer_auth_token.write'
  | 'customer_portal_session.write'
  | 'discount.read'
  | 'discount.write'
  | 'notification.read'
  | 'notification.write'
  | 'notification_setting.read'
  | 'notification_setting.write'
  | 'notification_simulation.read'
  | 'notification_simulation.write'
  | 'payment_method.read'
  | 'payment_method.write'
  | 'price.read'
  | 'price.write'
  | 'product.read'
  | 'product.write'
  | 'report.read'
  | 'report.write'
  | 'subscription.read'
  | 'subscription.write'
  | 'transaction.read'
  | 'transaction.write';
