/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type SavedPaymentMethodCardType } from '../../enums';

export interface ICardResponse {
  type: SavedPaymentMethodCardType;
  last4: string;
  expiry_month: number;
  expiry_year: number;
  cardholder_name: string;
}
