/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export interface IMetricsTimeseriesActiveSubscribersDatapoint {
  count: number;
  timestamp: string;
}
