/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMetricsTimeseriesCheckoutConversionDatapoint } from './metrics-timeseries-checkout-conversion-datapoint.js';

export interface IMetricsTimeseriesCheckoutConversionResponse {
  ends_at: string;
  interval: 'day';
  starts_at: string;
  timeseries: IMetricsTimeseriesCheckoutConversionDatapoint[];
  updated_at: string;
}
