/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMetricsTimeseriesChargebacksDatapoint } from './metrics-timeseries-chargebacks-datapoint.js';

export interface IMetricsTimeseriesChargebacksResponse {
  ends_at: string;
  interval: 'day';
  starts_at: string;
  timeseries: IMetricsTimeseriesChargebacksDatapoint[];
  updated_at: string;
}
