/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { TransactionsTimePeriodNotification } from './transactions-time-period-notification.js';
import { type ITransactionProrationNotificationResponse } from '../../types/index.js';

export class TransactionProrationNotification {
  public readonly rate: string;
  public readonly billingPeriod: TransactionsTimePeriodNotification | null;

  constructor(transactionProration: ITransactionProrationNotificationResponse) {
    this.rate = transactionProration.rate;
    this.billingPeriod = transactionProration.billing_period
      ? new TransactionsTimePeriodNotification(transactionProration.billing_period)
      : null;
  }
}
