/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITransactionLineItemNotificationResponse } from '../../types';
import {
  TransactionProrationNotification,
  UnitTotalsNotification,
  TotalsNotification,
  ProductNotification,
} from '../index';

export class TransactionLineItemNotification {
  public readonly id: string;
  public readonly priceId: string;
  public readonly quantity: number;
  public readonly proration: TransactionProrationNotification | null;
  public readonly taxRate: string;
  public readonly unitTotals: UnitTotalsNotification | null;
  public readonly totals: TotalsNotification | null;
  public readonly product: ProductNotification | null;

  constructor(transactionLineItem: ITransactionLineItemNotificationResponse) {
    this.id = transactionLineItem.id;
    this.priceId = transactionLineItem.price_id;
    this.quantity = transactionLineItem.quantity;
    this.proration = transactionLineItem.proration
      ? new TransactionProrationNotification(transactionLineItem.proration)
      : null;
    this.taxRate = transactionLineItem.tax_rate;
    this.unitTotals = transactionLineItem.unit_totals
      ? new UnitTotalsNotification(transactionLineItem.unit_totals)
      : null;
    this.totals = transactionLineItem.totals ? new TotalsNotification(transactionLineItem.totals) : null;
    this.product = transactionLineItem.product ? new ProductNotification(transactionLineItem.product) : null;
  }
}
