/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { PriceNotification } from '../price/index.js';
import { TransactionProrationNotification } from './transaction-proration-notification.js';
import { type ITransactionItemNotificationResponse } from '../../types/index.js';

export class TransactionItemNotification {
  public readonly price: PriceNotification | null;
  public readonly quantity: number;
  public readonly proration: TransactionProrationNotification | null;

  constructor(transactionItem: ITransactionItemNotificationResponse) {
    this.price = transactionItem.price ? new PriceNotification(transactionItem.price) : null;
    this.quantity = transactionItem.quantity;
    this.proration = transactionItem.proration ? new TransactionProrationNotification(transactionItem.proration) : null;
  }
}
