/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type SubscriptionConsentRequirementType = 'trial_ending' | 'introductory_discount_ending';
