/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ICreditBalanceResponse } from '../../types/index.js';
import { type CurrencyCode } from '../../enums/index.js';
import { CustomerBalance } from './customer-balance.js';

export class CreditBalance {
  public readonly customerId: string | null;
  public readonly currencyCode: CurrencyCode | null;
  public readonly balance: CustomerBalance | null;

  constructor(creditBalance: ICreditBalanceResponse) {
    this.customerId = creditBalance.customer_id ? creditBalance.customer_id : null;
    this.currencyCode = creditBalance.currency_code ? creditBalance.currency_code : null;
    this.balance = creditBalance.balance ? new CustomerBalance(creditBalance.balance) : null;
  }
}
