/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITimePeriod } from './time-period.js';

export interface IBillingDetailsResponse {
  enable_checkout?: boolean | null;
  purchase_order_number?: string | null;
  additional_information?: string | null;
  payment_terms: ITimePeriod;
}
