/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IAdjustmentOriginalAmountResponse } from './adjustment-original-amount-response.js';

export interface IChargebackFee {
  amount: string;
  original?: IAdjustmentOriginalAmountResponse | null;
}
