/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type ICustomData = Record<string, any>;
