/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { KoreanMarketUnderlyingPaymentMethodType } from '../../enums/index.js';

export interface IKoreanMarketUnderlyingDetails {
  type: KoreanMarketUnderlyingPaymentMethodType;
}
