/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { IKoreanMarketUnderlyingDetails } from './korean-market-underlying-details.js';

export interface IPaymentMethodUnderlyingDetails {
  korea_local: IKoreanMarketUnderlyingDetails;
}
