/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type SouthKoreaLocalCardType } from '../../enums/index.js';

export interface ISouthKoreaLocalCardResponse {
  type: SouthKoreaLocalCardType;
  last4: string;
}
