/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITotals } from '../index';

export interface ITaxRatesUsedResponse {
  tax_rate: string;
  totals?: ITotals | null;
}
