/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CurrencyCode } from '../../enums/index.js';

export interface ITransactionTotalsAdjustedResponse {
  subtotal: string;
  tax: string;
  total: string;
  grand_total: string;
  grand_total_tax: string;
  fee?: string | null;
  earnings?: string | null;
  currency_code: CurrencyCode;
  retained_fee: string;
}
