/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IProductResponse, type ITotals, type IUnitTotals } from '../index';

export interface ITransactionLineItemPreviewResponse {
  price_id: string;
  quantity: number;
  tax_rate: string;
  unit_totals: IUnitTotals;
  totals: ITotals;
  product: IProductResponse;
}
