/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITimePeriod } from './time-period.js';

export interface ITrialPeriodResponse extends ITimePeriod {
  requires_payment_method?: boolean;
}
