/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CountryCode } from '../../enums/index.js';
import { type IMoney } from './money.js';

export interface IUnitPriceOverride {
  countryCodes: CountryCode[];
  unitPrice: IMoney;
}
