/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMoneyResponse } from '../index';
import { type CountryCode } from '../../enums';

export interface IUnitPriceOverrideResponse {
  country_codes: CountryCode[];
  unit_price: IMoneyResponse;
}
