/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event';
import { PaymentMethodNotification } from '../../entities';
import { EventName } from '../../helpers';
import { type IEventsResponse } from '../../../types';
import { type IPaymentMethodNotificationResponse } from '../../types';

export class PaymentMethodDeletedEvent extends Event {
  public override readonly eventType = EventName.PaymentMethodDeleted;
  public override readonly data: PaymentMethodNotification;

  constructor(response: IEventsResponse<IPaymentMethodNotificationResponse>) {
    super(response);
    this.data = new PaymentMethodNotification(response.data);
  }
}
