/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type SubscriptionEffectiveFrom } from '../../../enums/index.js';

export interface CancelSubscription {
  effectiveFrom?: SubscriptionEffectiveFrom | null;
}
