/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export interface GetSubscriptionQueryParameters {
  include?: Array<'next_transaction' | 'recurring_transaction_details'>;
}
