/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import {
  type ActionSource,
  type ActorType,
  type SubscriptionHistoryAction,
  type SubscriptionHistoryReason,
} from '../../../enums/index.js';

export interface ListSubscriptionHistoryQueryParameters {
  action?: SubscriptionHistoryAction[];
  source?: ActionSource[];
  actorType?: ActorType[];
  actorId?: string[];
  reason?: SubscriptionHistoryReason[];
  occurredAt?: string;
  'occurredAt[LTE]'?: string;
  'occurredAt[GTE]'?: string;
  after?: string;
  perPage?: number;
  orderBy?: string;
}
