/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type SubscriptionOnResume } from '../../../enums/index.js';

export interface ResumeSubscription {
  effectiveFrom: 'immediately' | string;
  onResume?: SubscriptionOnResume;
}
