/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type DiscountMode, type DiscountStatus } from '../../../enums/index.js';

export interface ListDiscountQueryParameters {
  after?: string;
  code?: string[];
  id?: string[];
  orderBy?: string;
  perPage?: number;
  status?: DiscountStatus[];
  mode?: DiscountMode;
  discountGroupId?: string[];
  include?: Array<'discount_group'>;
}
