/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IAdjustmentItemNotificationResponse } from '../../types';
import { AdjustmentItemTotalsNotification, AdjustmentProrationNotification } from '../index';
import { type AdjustmentType } from '../../../enums';

export class AdjustmentItemNotification {
  public readonly id: string;
  public readonly itemId: string;
  public readonly type: AdjustmentType;
  public readonly amount: string | null;
  public readonly proration: AdjustmentProrationNotification | null;
  public readonly totals: AdjustmentItemTotalsNotification | null;

  constructor(adjustmentItem: IAdjustmentItemNotificationResponse) {
    this.id = adjustmentItem.id;
    this.itemId = adjustmentItem.item_id;
    this.type = adjustmentItem.type;
    this.amount = adjustmentItem.amount ? adjustmentItem.amount : null;
    this.proration = adjustmentItem.proration ? new AdjustmentProrationNotification(adjustmentItem.proration) : null;
    this.totals = adjustmentItem.totals ? new AdjustmentItemTotalsNotification(adjustmentItem.totals) : null;
  }
}
