/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IAdjustmentsTimePeriodNotificationResponse } from '../../types';

export class AdjustmentTimePeriodNotification {
  public readonly startsAt: string;
  public readonly endsAt: string;

  constructor(adjustmentsTimePeriod: IAdjustmentsTimePeriodNotificationResponse) {
    this.startsAt = adjustmentsTimePeriod.starts_at;
    this.endsAt = adjustmentsTimePeriod.ends_at;
  }
}
