/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IAdjustmentItemTotalsNotificationResponse } from '../../types';

export class AdjustmentItemTotalsNotification {
  public readonly subtotal: string;
  public readonly tax: string;
  public readonly total: string;

  constructor(adjustmentItemTotals: IAdjustmentItemTotalsNotificationResponse) {
    this.subtotal = adjustmentItemTotals.subtotal;
    this.tax = adjustmentItemTotals.tax;
    this.total = adjustmentItemTotals.total;
  }
}
