/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IAdjustmentsProrationNotificationResponse } from '../../types';
import { AdjustmentTimePeriodNotification } from '../index';

export class AdjustmentProrationNotification {
  public readonly rate: string;
  public readonly billingPeriod: AdjustmentTimePeriodNotification | null;

  constructor(adjustmentsProration: IAdjustmentsProrationNotificationResponse) {
    this.rate = adjustmentsProration.rate;
    this.billingPeriod = adjustmentsProration.billing_period
      ? new AdjustmentTimePeriodNotification(adjustmentsProration.billing_period)
      : null;
  }
}
