/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type NotificationStatus = 'not_attempted' | 'needs_retry' | 'delivered' | 'failed';
