/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event';
import { Payout } from '../../../entities';
import { EventName } from '../../helpers';
import { type IEventsResponse, type IPayoutResponse } from '../../../types';

export class PayoutPaidEvent extends Event {
  public override readonly eventType = EventName.PayoutPaid;
  public override readonly data: Payout;

  constructor(response: IEventsResponse<IPayoutResponse>) {
    super(response);
    this.data = new Payout(response.data);
  }
}
