/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IEventsResponse } from '../../types/index.js';

export class Event {
  public eventId: string;
  public notificationId: string | null;
  public eventType: string;
  public occurredAt: string;
  public data: object;

  constructor(eventData: IEventsResponse) {
    this.eventId = eventData.event_id;
    this.notificationId = eventData.notification_id ?? null;
    this.eventType = eventData.event_type;
    this.occurredAt = eventData.occurred_at;
    this.data = eventData.data;
  }
}
