/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { AdjustmentOriginalAmountNotification } from './adjustment-original-amount-notification.js';
import { type IChargebackFeeNotification } from '../../types/index.js';

export class ChargebackFeeNotification {
  public readonly amount: string;
  public readonly original: AdjustmentOriginalAmountNotification | null;

  constructor(chargebackFee: IChargebackFeeNotification) {
    this.amount = chargebackFee.amount;
    this.original = chargebackFee.original ? new AdjustmentOriginalAmountNotification(chargebackFee.original) : null;
  }
}
