/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IImportMetaNotificationResponse } from '../../types';

export class ImportMetaNotification {
  public readonly externalId: string | null;
  public readonly importedFrom: string;

  constructor(importMeta: IImportMetaNotificationResponse) {
    this.externalId = importMeta.external_id ? importMeta.external_id : null;
    this.importedFrom = importMeta.imported_from;
  }
}
