/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { IPaymentMethodUnderlyingDetailsNotification } from '../../types/index.js';
import { KoreanMarketUnderlyingDetailsNotification } from './korean-market-underlying-details-notification.js';

export class PaymentMethodUnderlyingDetailsNotification {
  public readonly koreaLocal: KoreanMarketUnderlyingDetailsNotification | null;

  constructor(paymentMethodUnderlyingDetails: IPaymentMethodUnderlyingDetailsNotification) {
    this.koreaLocal = paymentMethodUnderlyingDetails.korea_local
      ? new KoreanMarketUnderlyingDetailsNotification(paymentMethodUnderlyingDetails.korea_local)
      : null;
  }
}
