/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IPaymentMethodDetailsNotification } from '../../types';
import { type PaymentType } from '../../../enums';
import { PaymentCardNotification } from './payment-card-notification';

export class PaymentMethodDetailsNotification {
  public readonly type: PaymentType;
  public readonly card: PaymentCardNotification | null;

  constructor(paymentMethodDetails: IPaymentMethodDetailsNotification) {
    this.type = paymentMethodDetails.type;
    this.card = paymentMethodDetails.card ? new PaymentCardNotification(paymentMethodDetails.card) : null;
  }
}
