/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type SouthKoreaLocalCardType } from '../../../enums/index.js';
import { type ISouthKoreaLocalCardNotificationResponse } from '../../types/index.js';

export class SouthKoreaLocalCardNotification {
  public readonly type: SouthKoreaLocalCardType;
  public readonly last4: string;

  constructor(southKoreaLocalCard: ISouthKoreaLocalCardNotificationResponse) {
    this.type = southKoreaLocalCard.type;
    this.last4 = southKoreaLocalCard.last4;
  }
}
