/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type Interval } from '../../../enums/index.js';
import { type ITimePeriodNotification } from '../../types/index.js';

export class TimePeriodNotification {
  public readonly interval: Interval;
  public readonly frequency: number;

  constructor(timePeriod: ITimePeriodNotification) {
    this.interval = timePeriod.interval;
    this.frequency = timePeriod.frequency;
  }
}
