/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CurrencyCode } from '../../../enums/index.js';
import { type ITransactionTotalsAdjustedNotificationResponse } from '../../types/index.js';

export class TransactionTotalsAdjustedNotification {
  public readonly subtotal: string;
  public readonly tax: string;
  public readonly total: string;
  public readonly grandTotal: string;
  public readonly fee: string | null;
  public readonly earnings: string | null;
  public readonly currencyCode: CurrencyCode;
  public readonly retainedFee: string;

  constructor(transactionTotalsAdjusted: ITransactionTotalsAdjustedNotificationResponse) {
    this.subtotal = transactionTotalsAdjusted.subtotal;
    this.tax = transactionTotalsAdjusted.tax;
    this.total = transactionTotalsAdjusted.total;
    this.grandTotal = transactionTotalsAdjusted.grand_total;
    this.fee = transactionTotalsAdjusted.fee ? transactionTotalsAdjusted.fee : null;
    this.earnings = transactionTotalsAdjusted.earnings ? transactionTotalsAdjusted.earnings : null;
    this.currencyCode = transactionTotalsAdjusted.currency_code;
    this.retainedFee = transactionTotalsAdjusted.retained_fee;
  }
}
