/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CurrencyCode } from '../../../enums/index.js';
import { type ITransactionTotalsNotificationResponse } from '../../types/index.js';

export class TransactionTotalsNotification {
  public readonly subtotal: string;
  public readonly discount: string;
  public readonly tax: string;
  public readonly total: string;
  public readonly credit: string;
  public readonly creditToBalance: string;
  public readonly balance: string;
  public readonly grandTotal: string;
  public readonly fee: string | null;
  public readonly earnings: string | null;
  public readonly currencyCode: CurrencyCode;

  constructor(transactionTotals: ITransactionTotalsNotificationResponse) {
    this.subtotal = transactionTotals.subtotal;
    this.discount = transactionTotals.discount;
    this.tax = transactionTotals.tax;
    this.total = transactionTotals.total;
    this.credit = transactionTotals.credit;
    this.creditToBalance = transactionTotals.credit_to_balance;
    this.balance = transactionTotals.balance;
    this.grandTotal = transactionTotals.grand_total;
    this.fee = transactionTotals.fee ? transactionTotals.fee : null;
    this.earnings = transactionTotals.earnings ? transactionTotals.earnings : null;
    this.currencyCode = transactionTotals.currency_code;
  }
}
