/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { ChargebackFeeNotification } from './chargeback-fee-notification.js';
import { type PayoutCurrencyCode } from '../../../enums/index.js';
import { type ITransactionPayoutTotalsAdjustedNotificationResponse } from '../../types/index.js';

export class TransactionPayoutTotalsAdjustedNotification {
  public readonly subtotal: string;
  public readonly tax: string;
  public readonly total: string;
  public readonly fee: string;
  public readonly chargebackFee: ChargebackFeeNotification | null;
  public readonly earnings: string;
  public readonly currencyCode: PayoutCurrencyCode;
  public readonly exchangeRate: string;
  public readonly retainedFee: string;

  constructor(transactionPayoutTotalsAdjusted: ITransactionPayoutTotalsAdjustedNotificationResponse) {
    this.subtotal = transactionPayoutTotalsAdjusted.subtotal;
    this.tax = transactionPayoutTotalsAdjusted.tax;
    this.total = transactionPayoutTotalsAdjusted.total;
    this.fee = transactionPayoutTotalsAdjusted.fee;
    this.chargebackFee = transactionPayoutTotalsAdjusted.chargeback_fee
      ? new ChargebackFeeNotification(transactionPayoutTotalsAdjusted.chargeback_fee)
      : null;
    this.earnings = transactionPayoutTotalsAdjusted.earnings;
    this.currencyCode = transactionPayoutTotalsAdjusted.currency_code;
    this.exchangeRate = transactionPayoutTotalsAdjusted.exchange_rate;
    this.retainedFee = transactionPayoutTotalsAdjusted.retained_fee;
  }
}
