/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ISimulationTypeResponse } from '../../types/index.js';

export class SimulationType {
  public readonly name: string;
  public readonly label: string;
  public readonly description: string;
  public readonly group: string;
  public readonly type: string;
  public readonly events: any[];

  constructor(simulationTypeResponse: ISimulationTypeResponse) {
    this.name = simulationTypeResponse.name;
    this.label = simulationTypeResponse.label;
    this.description = simulationTypeResponse.description;
    this.group = simulationTypeResponse.group;
    this.type = simulationTypeResponse.type;
    this.events = simulationTypeResponse.events;
  }
}
