/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { getPaddleTestClient } from '../helpers/test-client.js';
import {
  CheckoutDomainMockResponse,
  ListCheckoutDomainsMockResponse,
  VerifyCheckoutDomainPaymentMethodExpectation,
  VerifyCheckoutDomainPaymentMethodMock,
} from '../mocks/resources/checkout-domains.mock.js';
import { CheckoutDomainsResource } from '../../resources/index.js';
import { convertToSnakeCase } from '../../internal/index.js';

const legacyDomainId = '9b95b0b8-e10f-441a-862e-1936a6d818ab';

describe('CheckoutDomainsResource', () => {
  test('should return a list of checkout domains', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(ListCheckoutDomainsMockResponse);

    const checkoutDomainsResource = new CheckoutDomainsResource(paddleInstance);
    const checkoutDomainCollection = checkoutDomainsResource.list();

    let checkoutDomains = await checkoutDomainCollection.next();
    expect(paddleInstance.get).toHaveBeenCalledWith('/checkout-domains?');
    expect(checkoutDomains).toHaveLength(1);
    expect(checkoutDomains[0]?.status).toBe('action_required');
    expect(checkoutDomains[0]?.paymentMethodVerification.applePay.status).toBe('verified');

    checkoutDomains = await checkoutDomainCollection.next();
    expect(paddleInstance.get).toHaveBeenCalledWith('/checkout-domains?after=1');
    expect(checkoutDomains).toHaveLength(1);
  });

  test('should get a checkout domain using a legacy domain ID', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(CheckoutDomainMockResponse);

    const checkoutDomainsResource = new CheckoutDomainsResource(paddleInstance);
    const checkoutDomain = await checkoutDomainsResource.get(legacyDomainId);

    expect(paddleInstance.get).toHaveBeenCalledWith(`/checkout-domains/${legacyDomainId}`);
    expect(checkoutDomain).toBeDefined();
  });

  test('should delete a checkout domain using a legacy domain ID', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.delete = jest.fn().mockResolvedValue(undefined);

    const checkoutDomainsResource = new CheckoutDomainsResource(paddleInstance);
    const checkoutDomain = await checkoutDomainsResource.delete(legacyDomainId);

    expect(paddleInstance.delete).toHaveBeenCalledWith(`/checkout-domains/${legacyDomainId}`);
    expect(checkoutDomain).toBeUndefined();
  });

  test('should verify a payment method using a legacy domain ID', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.post = jest.fn().mockResolvedValue(CheckoutDomainMockResponse);

    const checkoutDomainsResource = new CheckoutDomainsResource(paddleInstance);
    const checkoutDomain = await checkoutDomainsResource.verifyPaymentMethod(
      legacyDomainId,
      VerifyCheckoutDomainPaymentMethodMock,
    );

    expect(paddleInstance.post).toHaveBeenCalledWith(
      `/checkout-domains/${legacyDomainId}/verify-payment-method`,
      VerifyCheckoutDomainPaymentMethodMock,
    );
    expect(checkoutDomain).toBeDefined();
    expect(convertToSnakeCase(VerifyCheckoutDomainPaymentMethodMock)).toEqual(
      VerifyCheckoutDomainPaymentMethodExpectation,
    );
  });
});
