/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { getPaddleTestClient } from '../helpers/test-client.js';
import {
  ActiveSubscribersMock,
  ActiveSubscribersMockResponse,
  MonthlyRecurringRevenueChangeMockResponse,
  MonthlyRecurringRevenueMock,
  MonthlyRecurringRevenueMockResponse,
  ChargebacksMock,
  ChargebacksMockResponse,
  RefundsMock,
  RefundsMockResponse,
  RevenueMock,
  RevenueMockResponse,
} from '../mocks/resources/metrics.mock.js';
import {
  GetActiveSubscribersQueryParameters,
  GetChargebacksQueryParameters,
  GetMonthlyRecurringRevenueChangeQueryParameters,
  GetMonthlyRecurringRevenueQueryParameters,
  GetRefundsQueryParameters,
  GetRevenueQueryParameters,
  MetricsResource,
} from '../../resources/index.js';

describe('MetricsResource', () => {
  test('should return active subscribers metrics', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(ActiveSubscribersMockResponse);

    const metricsResource = new MetricsResource(paddleInstance);
    const queryParams: GetActiveSubscribersQueryParameters = {
      from: '2025-01-01',
      to: '2025-01-14',
    };

    const result = await metricsResource.getActiveSubscribers(queryParams);

    expect(paddleInstance.get).toHaveBeenCalledWith('/metrics/active-subscribers', {
      queryParameters: queryParams,
    });
    expect(result).toBeDefined();
    expect(result.endsAt).toBe(ActiveSubscribersMock.ends_at);
    expect(result.startsAt).toBe(ActiveSubscribersMock.starts_at);
    expect(result.interval).toBe('day');
    expect(result.updatedAt).toBe(ActiveSubscribersMock.updated_at);
    expect(result.timeseries).toHaveLength(2);
    expect(result.timeseries[0].count).toBe(100);
    expect(result.timeseries[0].timestamp).toBe('2025-01-01T00:00:00Z');
    expect(result.timeseries[1].count).toBe(105);
    expect(result.timeseries[1].timestamp).toBe('2025-01-02T00:00:00Z');
  });

  test('should return empty timeseries when from and to are the same', async () => {
    const emptyTimeseriesResponse = {
      data: {
        ends_at: '2025-01-01T00:00:00Z',
        interval: 'day' as const,
        starts_at: '2025-01-01T00:00:00Z',
        timeseries: [],
        updated_at: '2025-01-01T12:00:00Z',
      },
      meta: {
        request_id: '',
      },
    };

    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(emptyTimeseriesResponse);

    const metricsResource = new MetricsResource(paddleInstance);
    const queryParams: GetActiveSubscribersQueryParameters = {
      from: '2025-01-01',
      to: '2025-01-01',
    };

    const result = await metricsResource.getActiveSubscribers(queryParams);

    expect(result).toBeDefined();
    expect(result.timeseries).toHaveLength(0);
  });

  test('should return monthly recurring revenue metrics', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(MonthlyRecurringRevenueMockResponse);

    const metricsResource = new MetricsResource(paddleInstance);
    const queryParams: GetMonthlyRecurringRevenueQueryParameters = {
      from: '2025-01-01',
      to: '2025-01-14',
    };

    const result = await metricsResource.getMonthlyRecurringRevenue(queryParams);

    expect(paddleInstance.get).toHaveBeenCalledWith('/metrics/monthly-recurring-revenue', {
      queryParameters: queryParams,
    });
    expect(result).toBeDefined();
    expect(result.currencyCode).toBe(MonthlyRecurringRevenueMock.currency_code);
    expect(result.endsAt).toBe(MonthlyRecurringRevenueMock.ends_at);
    expect(result.startsAt).toBe(MonthlyRecurringRevenueMock.starts_at);
    expect(result.interval).toBe('day');
    expect(result.updatedAt).toBe(MonthlyRecurringRevenueMock.updated_at);
    expect(result.timeseries).toHaveLength(2);
    expect(result.timeseries[0].amount).toBe('10000');
    expect(result.timeseries[0].timestamp).toBe('2025-01-01T00:00:00Z');
    expect(result.timeseries[1].amount).toBe('10500');
    expect(result.timeseries[1].timestamp).toBe('2025-01-02T00:00:00Z');
  });

  test('should return empty MRR timeseries when from and to are the same', async () => {
    const emptyMrrResponse = {
      data: {
        currency_code: 'USD' as const,
        ends_at: '2025-01-01T00:00:00Z',
        interval: 'day' as const,
        starts_at: '2025-01-01T00:00:00Z',
        timeseries: [],
        updated_at: '2025-01-01T12:00:00Z',
      },
      meta: {
        request_id: '',
      },
    };

    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(emptyMrrResponse);

    const metricsResource = new MetricsResource(paddleInstance);
    const queryParams: GetMonthlyRecurringRevenueQueryParameters = {
      from: '2025-01-01',
      to: '2025-01-01',
    };

    const result = await metricsResource.getMonthlyRecurringRevenue(queryParams);

    expect(result).toBeDefined();
    expect(result.timeseries).toHaveLength(0);
  });

  test('should return monthly recurring revenue change metrics', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(MonthlyRecurringRevenueChangeMockResponse);

    const metricsResource = new MetricsResource(paddleInstance);
    const queryParams: GetMonthlyRecurringRevenueChangeQueryParameters = {
      from: '2025-01-01',
      to: '2025-01-14',
    };

    const result = await metricsResource.getMonthlyRecurringRevenueChange(queryParams);

    expect(paddleInstance.get).toHaveBeenCalledWith('/metrics/monthly-recurring-revenue-change', {
      queryParameters: queryParams,
    });
    expect(result).toBeDefined();
    expect(result.currencyCode).toBe(MonthlyRecurringRevenueMock.currency_code);
    expect(result.endsAt).toBe(MonthlyRecurringRevenueMock.ends_at);
    expect(result.startsAt).toBe(MonthlyRecurringRevenueMock.starts_at);
    expect(result.interval).toBe('day');
    expect(result.updatedAt).toBe(MonthlyRecurringRevenueMock.updated_at);
    expect(result.timeseries).toHaveLength(2);
    expect(result.timeseries[0].amount).toBe('10000');
    expect(result.timeseries[0].timestamp).toBe('2025-01-01T00:00:00Z');
    expect(result.timeseries[1].amount).toBe('10500');
    expect(result.timeseries[1].timestamp).toBe('2025-01-02T00:00:00Z');
  });

  test('should return revenue metrics', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(RevenueMockResponse);

    const metricsResource = new MetricsResource(paddleInstance);
    const queryParams: GetRevenueQueryParameters = {
      from: '2025-01-01',
      to: '2025-01-14',
    };

    const result = await metricsResource.getRevenue(queryParams);

    expect(paddleInstance.get).toHaveBeenCalledWith('/metrics/revenue', {
      queryParameters: queryParams,
    });
    expect(result).toBeDefined();
    expect(result.currencyCode).toBe(RevenueMock.currency_code);
    expect(result.endsAt).toBe(RevenueMock.ends_at);
    expect(result.startsAt).toBe(RevenueMock.starts_at);
    expect(result.interval).toBe('day');
    expect(result.updatedAt).toBe(RevenueMock.updated_at);
    expect(result.timeseries).toHaveLength(2);
    expect(result.timeseries[0].amount).toBe('5000');
    expect(result.timeseries[0].count).toBe(3);
    expect(result.timeseries[0].timestamp).toBe('2025-01-01T00:00:00Z');
    expect(result.timeseries[1].amount).toBe('7200');
    expect(result.timeseries[1].count).toBe(5);
    expect(result.timeseries[1].timestamp).toBe('2025-01-02T00:00:00Z');
  });

  test('should return refunds metrics', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(RefundsMockResponse);

    const metricsResource = new MetricsResource(paddleInstance);
    const queryParams: GetRefundsQueryParameters = {
      from: '2025-01-01',
      to: '2025-01-14',
    };

    const result = await metricsResource.getRefunds(queryParams);

    expect(paddleInstance.get).toHaveBeenCalledWith('/metrics/refunds', {
      queryParameters: queryParams,
    });
    expect(result).toBeDefined();
    expect(result.currencyCode).toBe(RefundsMock.currency_code);
    expect(result.endsAt).toBe(RefundsMock.ends_at);
    expect(result.startsAt).toBe(RefundsMock.starts_at);
    expect(result.interval).toBe('day');
    expect(result.updatedAt).toBe(RefundsMock.updated_at);
    expect(result.timeseries).toHaveLength(2);
    expect(result.timeseries[0].amount).toBe('1200');
    expect(result.timeseries[0].timestamp).toBe('2025-01-01T00:00:00Z');
    expect(result.timeseries[1].amount).toBe('800');
    expect(result.timeseries[1].timestamp).toBe('2025-01-02T00:00:00Z');
  });

  test('should return chargebacks metrics', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(ChargebacksMockResponse);

    const metricsResource = new MetricsResource(paddleInstance);
    const queryParams: GetChargebacksQueryParameters = {
      from: '2025-01-01',
      to: '2025-01-14',
    };

    const result = await metricsResource.getChargebacks(queryParams);

    expect(paddleInstance.get).toHaveBeenCalledWith('/metrics/chargebacks', {
      queryParameters: queryParams,
    });
    expect(result).toBeDefined();
    expect(result.endsAt).toBe(ChargebacksMock.ends_at);
    expect(result.startsAt).toBe(ChargebacksMock.starts_at);
    expect(result.interval).toBe('day');
    expect(result.updatedAt).toBe(ChargebacksMock.updated_at);
    expect(result.timeseries).toHaveLength(2);
    expect(result.timeseries[0].count).toBe(1);
    expect(result.timeseries[0].timestamp).toBe('2025-01-01T00:00:00Z');
    expect(result.timeseries[1].count).toBe(0);
    expect(result.timeseries[1].timestamp).toBe('2025-01-02T00:00:00Z');
  });
});
