/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { getPaddleTestClient } from '../helpers/test-client';
import { SimulationTypesResource } from '../../resources';
import { ListSimulationTypeMockResponse } from '../mocks/resources/simulation-types.mock';

describe('simulationTypesResource', () => {
  test('should return a list of simulations', async () => {
    const paddleInstance = getPaddleTestClient();
    paddleInstance.get = jest.fn().mockResolvedValue(ListSimulationTypeMockResponse);

    const simulationsResource = new SimulationTypesResource(paddleInstance);
    const simulationTypes = await simulationsResource.list();

    expect(paddleInstance.get).toBeCalledWith('/simulation-types');
    expect(simulationTypes.length).toBe(49);
  });
});
