/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IDiscountResponse } from '../../types/index.js';
import { Collection } from '../../internal/base/index.js';
import { Discount } from './discount.js';

export class DiscountCollection extends Collection<IDiscountResponse, Discount> {
  override fromJson(data: IDiscountResponse): Discount {
    return new Discount(data);
  }
}
