/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { SimulationRunEvent } from '../../entities';
import { type ISimulationRunEventResponse } from '../../types';
import { Collection } from '../../internal/base';

export class SimulationRunEventCollection extends Collection<ISimulationRunEventResponse, SimulationRunEvent> {
  override fromJson(data: ISimulationRunEventResponse): SimulationRunEvent {
    return new SimulationRunEvent(data);
  }
}
