/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { SubscriptionTimePeriod } from './subscription-time-period.js';
import { TransactionDetailsPreview } from './transaction-details-preview.js';
import { NextTransactionAdjustmentPreview } from './next-transaction-adjustment-preview.js';
import { type INextTransactionResponse } from '../../types/index.js';

export class NextTransaction {
  public readonly billingPeriod: SubscriptionTimePeriod;
  public readonly details: TransactionDetailsPreview;
  public readonly adjustments: NextTransactionAdjustmentPreview[];

  constructor(nextTransaction: INextTransactionResponse) {
    this.billingPeriod = new SubscriptionTimePeriod(nextTransaction.billing_period);
    this.details = new TransactionDetailsPreview(nextTransaction.details);
    this.adjustments = nextTransaction.adjustments.map(
      (adjustment) => new NextTransactionAdjustmentPreview(adjustment),
    );
  }
}
