/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type AdjustmentItemType } from '../../enums/index.js';
import { AdjustmentItemTotals, AdjustmentProration } from '../adjustment/index.js';
import { type IAdjustmentItemResponse } from '../../types/index.js';

export class NextTransactionAdjustmentItem {
  public readonly itemId: string;
  public readonly type: AdjustmentItemType;
  public readonly amount: string | null;
  public readonly proration: AdjustmentProration | null;
  public readonly totals: AdjustmentItemTotals | null;

  constructor(adjustmentItem: IAdjustmentItemResponse) {
    this.itemId = adjustmentItem.item_id;
    this.type = adjustmentItem.type;
    this.amount = adjustmentItem.amount ? adjustmentItem.amount : null;
    this.proration = adjustmentItem.proration ? new AdjustmentProration(adjustmentItem.proration) : null;
    this.totals = adjustmentItem.totals ? new AdjustmentItemTotals(adjustmentItem.totals) : null;
  }
}
