/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type INextTransactionResponse } from '../../types';
import { SubscriptionTimePeriod, TransactionDetailsPreview, NextTransactionAdjustmentPreview } from '../index';

export class NextTransaction {
  public readonly billingPeriod: SubscriptionTimePeriod;
  public readonly details: TransactionDetailsPreview;
  public readonly adjustments: NextTransactionAdjustmentPreview[];

  constructor(nextTransaction: INextTransactionResponse) {
    this.billingPeriod = new SubscriptionTimePeriod(nextTransaction.billing_period);
    this.details = new TransactionDetailsPreview(nextTransaction.details);
    this.adjustments = nextTransaction.adjustments.map(
      (adjustment) => new NextTransactionAdjustmentPreview(adjustment),
    );
  }
}
