/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ISubscriptionPreviewUpdateSummary } from '../../types';
import { Money, SubscriptionPreviewSummaryResult } from '../index';

export class SubscriptionPreviewUpdateSummary {
  public readonly credit: Money;
  public readonly charge: Money;
  public readonly result: SubscriptionPreviewSummaryResult;

  constructor(previewUpdateSummary: ISubscriptionPreviewUpdateSummary) {
    this.credit = new Money(previewUpdateSummary.credit);
    this.charge = new Money(previewUpdateSummary.charge);
    this.result = new SubscriptionPreviewSummaryResult(previewUpdateSummary.result);
  }
}
