/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Collection } from '../../internal/base/index.js';
import { type ISubscriptionResponse } from '../../types/index.js';
import { Subscription } from './subscription.js';

export class SubscriptionCollection extends Collection<ISubscriptionResponse, Subscription> {
  override fromJson(data: ISubscriptionResponse): Subscription {
    return new Subscription(data);
  }
}
