/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Subscription } from './subscription';
import { type ISubscriptionResponse } from '../../types';
import { Collection } from '../../internal/base';

export class SubscriptionCollection extends Collection<ISubscriptionResponse, Subscription> {
  override fromJson(data: ISubscriptionResponse): Subscription {
    return new Subscription(data);
  }
}
