/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITransactionDetailsPreviewResponse } from '../../types';
import { TaxRatesUsed, TransactionTotals, TransactionLineItemPreview } from '../index';

export class TransactionDetailsPreview {
  public readonly taxRatesUsed: TaxRatesUsed[];
  public readonly totals: TransactionTotals;
  public readonly lineItems: TransactionLineItemPreview[];

  constructor(transactionDetailsPreview: ITransactionDetailsPreviewResponse) {
    this.taxRatesUsed = transactionDetailsPreview.tax_rates_used.map(
      (tax_rates_used) => new TaxRatesUsed(tax_rates_used),
    );
    this.totals = new TransactionTotals(transactionDetailsPreview.totals);
    this.lineItems = transactionDetailsPreview.line_items.map((line_item) => new TransactionLineItemPreview(line_item));
  }
}
