/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Business } from './business';
import { type IBusinessResponse } from '../../types';
import { Collection } from '../../internal/base';

export class BusinessCollection extends Collection<IBusinessResponse, Business> {
  override fromJson(data: IBusinessResponse): Business {
    return new Business(data);
  }
}
