/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type ActorType = 'customer' | 'user' | 'api_key' | 'paddle_staff' | 'publisher' | 'system';
