/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type AvailablePaymentMethod =
  | 'alipay'
  | 'apple_pay'
  | 'bancontact'
  | 'blik'
  | 'card'
  | 'google_pay'
  | 'ideal'
  | 'korea_local'
  | 'mb_way'
  | 'paypal'
  | 'pix'
  | 'upi';
