/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */
export type CurrencyCode =
  | 'USD'
  | 'EUR'
  | 'GBP'
  | 'JPY'
  | 'AUD'
  | 'CAD'
  | 'CHF'
  | 'HKD'
  | 'SGD'
  | 'SEK'
  | 'ARS'
  | 'BRL'
  | 'CNY'
  | 'COP'
  | 'CZK'
  | 'DKK'
  | 'HUF'
  | 'ILS'
  | 'INR'
  | 'KRW'
  | 'MXN'
  | 'NOK'
  | 'NZD'
  | 'PLN'
  | 'RUB'
  | 'THB'
  | 'TRY'
  | 'TWD'
  | 'UAH'
  | 'ZAR';
