/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type KoreanMarketUnderlyingPaymentMethodType =
  | 'bc'
  | 'citi'
  | 'hana'
  | 'hyundai'
  | 'jeju'
  | 'jeonbuk'
  | 'kakaobank'
  | 'kakaopay'
  | 'kbank'
  | 'kdbbank'
  | 'kookmin'
  | 'kwangju'
  | 'lotte'
  | 'mg'
  | 'naverpaycard'
  | 'naverpaypoint'
  | 'nh'
  | 'payco'
  | 'post'
  | 'samsung'
  | 'samsungpay'
  | 'savingsbank'
  | 'shinhan'
  | 'shinhyup'
  | 'suhyup'
  | 'tossbank'
  | 'unknown'
  | 'woori';
