/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type PaymentAttemptStatus =
  | 'authorized'
  | 'authorized_flagged'
  | 'canceled'
  | 'captured'
  | 'error'
  | 'action_required'
  | 'pending_no_action_required'
  | 'created'
  | 'unknown'
  | 'dropped';
