/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export type TaxCategory =
  | 'digital-goods'
  | 'ebooks'
  | 'implementation-services'
  | 'professional-services'
  | 'saas'
  | 'software-programming-services'
  | 'standard'
  | 'training-services'
  | 'website-hosting';
