/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type SimulationKind } from '../../enums';
import { type IEventName } from '../../notifications';

export interface ISimulationTypeResponse {
  name: string;
  label: string;
  description: string;
  group: string;
  type: SimulationKind;
  events: IEventName[];
}
