/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

export interface ICustomerPortalSubscriptionUrl {
  id: string;
  cancel_subscription: string;
  update_subscription_payment_method: string;
}
