/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IUrlsResponse } from './urls.js';

export interface ICustomerPortalSessionResponse {
  id: string;
  customer_id: string;
  urls: IUrlsResponse;
  created_at: string;
}
