/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IGeneralResponse } from './general.js';
import { type ICustomerPortalSubscriptionUrl } from './customer-portal-subscription-url.js';

export interface IUrlsResponse {
  general: IGeneralResponse;
  subscriptions: ICustomerPortalSubscriptionUrl[];
}
