/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IEventsResponse } from '../../../types/index.js';
import { IApiKeyExposureNotificationResponse } from '../../../notifications/index.js';

export const ApiKeyExposureCreatedMock: IEventsResponse<IApiKeyExposureNotificationResponse> = {
  event_id: 'evt_01jkdr0rc527wcjdg1txsdxhtg',
  event_type: 'api_key_exposure.created',
  occurred_at: '2025-06-24T12:58:38.746382Z',
  notification_id: 'ntf_01jkdr1mgbe62eqkh3p0fq8b0w',
  data: {
    id: 'apikeyexp_01jkdpbhazdpn3wpcya45as9tg',
    api_key_id: 'apikey_01jkdpbhazdpn3wpcya45as9tg',
    risk_level: 'high',
    action_taken: 'revoked',
    source: 'github',
    reference: 'https://github.com/example/repo/blob/main/config.js',
    description: 'API key found exposed in public GitHub repository.',
    created_at: '2025-06-24T12:58:38.746382Z',
  },
};

export const ApiKeyExposureCreatedMockExpectation = {
  eventId: 'evt_01jkdr0rc527wcjdg1txsdxhtg',
  eventType: 'api_key_exposure.created',
  occurredAt: '2025-06-24T12:58:38.746382Z',
  notificationId: 'ntf_01jkdr1mgbe62eqkh3p0fq8b0w',
  data: {
    id: 'apikeyexp_01jkdpbhazdpn3wpcya45as9tg',
    apiKeyId: 'apikey_01jkdpbhazdpn3wpcya45as9tg',
    riskLevel: 'high',
    actionTaken: 'revoked',
    source: 'github',
    reference: 'https://github.com/example/repo/blob/main/config.js',
    description: 'API key found exposed in public GitHub repository.',
    createdAt: '2025-06-24T12:58:38.746382Z',
  },
};
