/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IEventsResponse } from '../../../types/index.js';
import { IApiKeyNotificationResponse } from '../../../notifications/index.js';

export const ApiKeyExpiringMock: IEventsResponse<IApiKeyNotificationResponse> = {
  event_id: 'evt_01jkdr0rc527wcjdg1txsdxhtj',
  event_type: 'api_key.expiring',
  occurred_at: '2025-06-21T06:58:38.517522Z',
  notification_id: 'ntf_01jkdr1mgbe62eqkh3p0fq8b0m',
  data: {
    id: 'apikey_01jkdpbhazdpn3wpcya45as9tg',
    name: 'CRM integration',
    description: 'Used to authenticate with the API for storing Paddle customer data in our CRM.',
    status: 'active',
    key: 'pdl_live_apikey_01jkdpbhaz****',
    permissions: ['address.read', 'business.read', 'customer.read', 'subscription.read', 'transaction.read'],
    expires_at: '2025-06-26T06:58:38.517522Z',
    last_used_at: '2025-06-21T05:46:53.238201Z',
    created_at: '2025-03-26T06:58:38.517522Z',
    updated_at: '2025-03-26T06:58:38.517522Z',
  },
};

export const ApiKeyExpiringMockExpectation = {
  eventId: 'evt_01jkdr0rc527wcjdg1txsdxhtj',
  eventType: 'api_key.expiring',
  occurredAt: '2025-06-21T06:58:38.517522Z',
  notificationId: 'ntf_01jkdr1mgbe62eqkh3p0fq8b0m',
  data: {
    id: 'apikey_01jkdpbhazdpn3wpcya45as9tg',
    name: 'CRM integration',
    description: 'Used to authenticate with the API for storing Paddle customer data in our CRM.',
    status: 'active',
    key: 'pdl_live_apikey_01jkdpbhaz****',
    permissions: ['address.read', 'business.read', 'customer.read', 'subscription.read', 'transaction.read'],
    expiresAt: '2025-06-26T06:58:38.517522Z',
    lastUsedAt: '2025-06-21T05:46:53.238201Z',
    createdAt: '2025-03-26T06:58:38.517522Z',
    updatedAt: '2025-03-26T06:58:38.517522Z',
  },
};
