/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IEventsResponse, type IBusinessResponse } from '../../../types';

export const BusinessUpdatedMock: IEventsResponse<IBusinessResponse> = {
  event_id: 'evt_01h84b8sq18asjb0m3tvn4g0dn',
  event_type: 'business.updated',
  occurred_at: '2023-08-18T12:52:35.169192Z',
  notification_id: 'ntf_01h84b8ss7b9bza3c831md1a4d',
  data: {
    id: 'biz_01h84a7hr4pzhsajkm8tev89ev',
    name: 'ChatApp Inc.',
    status: 'active',
    contacts: [
      { name: 'Parker Jones', email: 'parker@example.com' },
      { name: 'Jo Riley', email: 'jo@example.com' },
      { name: 'Jesse Garcia', email: 'jo@example.com' },
    ],
    custom_data: { customer_reference_id: 'abcd1234' },
    created_at: '2023-08-18T12:34:25.668Z',
    updated_at: '2023-08-18T12:52:34.871482Z',
    company_number: '555775291485',
    tax_identifier: '555952383',
  },
};

export const BusinessUpdatedMockExpectation = {
  data: {
    companyNumber: '555775291485',
    contacts: [
      {
        email: 'parker@example.com',
        name: 'Parker Jones',
      },
      {
        email: 'jo@example.com',
        name: 'Jo Riley',
      },
      {
        email: 'jo@example.com',
        name: 'Jesse Garcia',
      },
    ],
    createdAt: '2023-08-18T12:34:25.668Z',
    customData: {
      customer_reference_id: 'abcd1234',
    },
    id: 'biz_01h84a7hr4pzhsajkm8tev89ev',
    importMeta: null,
    name: 'ChatApp Inc.',
    status: 'active',
    taxIdentifier: '555952383',
    updatedAt: '2023-08-18T12:52:34.871482Z',
  },
  eventId: 'evt_01h84b8sq18asjb0m3tvn4g0dn',
  eventType: 'business.updated',
  notificationId: 'ntf_01h84b8ss7b9bza3c831md1a4d',
  occurredAt: '2023-08-18T12:52:35.169192Z',
};
