/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { IBusinessNotificationResponse } from '../../../notifications/index.js';
import { IEventsResponse } from '../../../types/index.js';

export const BusinessImportedMock: IEventsResponse<IBusinessNotificationResponse> = {
  event_id: 'evt_01hhvz7k9kekw1wfxw8v8gbqcy',
  event_type: 'business.imported',
  occurred_at: '2023-08-18T12:34:25.964234Z',
  notification_id: 'ntf_01hhvz7kcr2nv50zddzx4w4sgx',
  data: {
    id: 'biz_01h84a7hr4pzhsajkm8tev89ev',
    name: 'ChatApp Inc.',
    status: 'active',
    contacts: [{ name: 'Parker Jones', email: 'parker@example.com' }],
    custom_data: { customer_reference_id: 'abcd1234' },
    created_at: '2023-08-18T12:34:25.668Z',
    updated_at: '2023-08-18T12:34:25.668Z',
    company_number: '555775291485',
    tax_identifier: '555952383',
    import_meta: { external_id: '1fc0727f-d3d5-43a0-907a-f3c002535ca0', imported_from: 'billing_platform' },
  },
};

export const BusinessImportedMockExpectation = {
  data: {
    companyNumber: '555775291485',
    contacts: [
      {
        email: 'parker@example.com',
        name: 'Parker Jones',
      },
    ],
    createdAt: '2023-08-18T12:34:25.668Z',
    customData: {
      customer_reference_id: 'abcd1234',
    },
    customerId: null,
    id: 'biz_01h84a7hr4pzhsajkm8tev89ev',
    importMeta: {
      externalId: '1fc0727f-d3d5-43a0-907a-f3c002535ca0',
      importedFrom: 'billing_platform',
    },
    name: 'ChatApp Inc.',
    status: 'active',
    taxIdentifier: '555952383',
    updatedAt: '2023-08-18T12:34:25.668Z',
  },
  eventId: 'evt_01hhvz7k9kekw1wfxw8v8gbqcy',
  eventType: 'business.imported',
  notificationId: 'ntf_01hhvz7kcr2nv50zddzx4w4sgx',
  occurredAt: '2023-08-18T12:34:25.964234Z',
};
