/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { IClientTokenNotificationResponse } from '../../../notifications/index.js';
import { IEventsResponse } from '../../../types/index.js';

export const ClientTokenCreatedMock: IEventsResponse<IClientTokenNotificationResponse> = {
  event_id: 'evt_01jkdr0rc527wcjdg1txsdxhtf',
  event_type: 'client_token.created',
  occurred_at: '2025-06-26T14:36:14.695521Z',
  notification_id: 'ntf_01jkdr1mgbe62eqkh3p0fq8b0h',
  data: {
    id: 'ctkn_01ghbkd0frb9k95cnhwd1bxpvk',
    token: 'live_7d279f61a3499fed520f7cd8c08',
    name: 'Pricing page integration',
    description: 'Used to display prices and open checkout within our pricing page on our marketing domain.',
    status: 'active',
    created_at: '2025-06-26T14:36:14.695521Z',
    updated_at: '2025-06-26T14:36:14.695521Z',
    revoked_at: null,
  },
};

export const ClientTokenCreatedMockExpectation = {
  data: {
    id: 'ctkn_01ghbkd0frb9k95cnhwd1bxpvk',
    token: 'live_7d279f61a3499fed520f7cd8c08',
    name: 'Pricing page integration',
    description: 'Used to display prices and open checkout within our pricing page on our marketing domain.',
    status: 'active',
    createdAt: '2025-06-26T14:36:14.695521Z',
    updatedAt: '2025-06-26T14:36:14.695521Z',
    revokedAt: null,
  },
  eventId: 'evt_01jkdr0rc527wcjdg1txsdxhtf',
  eventType: 'client_token.created',
  occurredAt: '2025-06-26T14:36:14.695521Z',
  notificationId: 'ntf_01jkdr1mgbe62eqkh3p0fq8b0h',
};
