/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { IClientTokenNotificationResponse } from '../../../notifications/index.js';
import { IEventsResponse } from '../../../types/index.js';

export const ClientTokenRevokedMock: IEventsResponse<IClientTokenNotificationResponse> = {
  event_id: 'evt_01jkdr0rc527wcjdg1txsdxhtf',
  event_type: 'client_token.revoked',
  occurred_at: '2025-06-27T11:26:10.253482Z',
  notification_id: 'ntf_01jkb92mpl7v4rfg8x3q5wz7bn',
  data: {
    id: 'ctkn_01ghbkd0frb9k95cnhwd1bxpvk',
    token: 'live_7d279f61a3499fed520f7cd8c08',
    name: 'Pricing page integration',
    description: 'Used to display prices and open checkout within our pricing page on our marketing domain.',
    status: 'revoked',
    created_at: '2025-06-26T14:36:14.695521Z',
    updated_at: '2025-06-27T11:26:10.253482Z',
    revoked_at: '2025-06-27T11:26:10.253482Z',
  },
};

export const ClientTokenRevokedMockExpectation = {
  data: {
    id: 'ctkn_01ghbkd0frb9k95cnhwd1bxpvk',
    token: 'live_7d279f61a3499fed520f7cd8c08',
    name: 'Pricing page integration',
    description: 'Used to display prices and open checkout within our pricing page on our marketing domain.',
    status: 'revoked',
    createdAt: '2025-06-26T14:36:14.695521Z',
    updatedAt: '2025-06-27T11:26:10.253482Z',
    revokedAt: '2025-06-27T11:26:10.253482Z',
  },
  eventId: 'evt_01jkdr0rc527wcjdg1txsdxhtf',
  eventType: 'client_token.revoked',
  occurredAt: '2025-06-27T11:26:10.253482Z',
  notificationId: 'ntf_01jkb92mpl7v4rfg8x3q5wz7bn',
};
