/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { IDiscountResponse, IEventsResponse } from '../../../types/index.js';

export const DiscountCreatedMock: IEventsResponse<IDiscountResponse> = {
  event_id: 'evt_01h8441jx8x1q971q9ksksqh82',
  event_type: 'discount.created',
  occurred_at: '2023-08-18T10:46:18.792661Z',
  notification_id: 'ntf_01h8441jz6fr97hv7zemswj8cw',
  data: {
    id: 'dsc_01h8441jn5pcwrfhwh78jqt8hk',
    status: 'active',
    description: 'New customer discount',
    enabled_for_checkout: true,
    code: 'SG6JNMJQ3D',
    type: 'flat',
    amount: '5000',
    currency_code: 'USD',
    recur: false,
    times_used: 0,
    maximum_recurring_intervals: null,
    usage_limit: 100,
    restrict_to: ['pro_01h90yj132e28vzwsrdc83927j'],
    custom_data: null,
    import_meta: null,
    expires_at: '2024-08-15T00:00:00.000Z',
    created_at: '2023-08-18T10:46:18.792Z',
    updated_at: '2023-08-18T10:46:18.792Z',
  },
};

export const DiscountCreatedMockExpectation = {
  data: {
    amount: '5000',
    code: 'SG6JNMJQ3D',
    createdAt: '2023-08-18T10:46:18.792Z',
    currencyCode: 'USD',
    customData: null,
    description: 'New customer discount',
    enabledForCheckout: true,
    expiresAt: '2024-08-15T00:00:00.000Z',
    id: 'dsc_01h8441jn5pcwrfhwh78jqt8hk',
    importMeta: null,
    maximumRecurringIntervals: null,
    recur: false,
    restrictTo: ['pro_01h90yj132e28vzwsrdc83927j'],
    status: 'active',
    timesUsed: 0,
    type: 'flat',
    updatedAt: '2023-08-18T10:46:18.792Z',
    usageLimit: 100,
  },
  eventId: 'evt_01h8441jx8x1q971q9ksksqh82',
  eventType: 'discount.created',
  notificationId: 'ntf_01h8441jz6fr97hv7zemswj8cw',
  occurredAt: '2023-08-18T10:46:18.792661Z',
};
