/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IEventsResponse, type IPaymentMethodResponse } from '../../../types';

export const PaymentMethodSavedMock: IEventsResponse<IPaymentMethodResponse> = {
  event_id: 'evt_01hwvkmsge7bhq1a31s35784zt',
  event_type: 'payment_method.saved',
  occurred_at: '2024-05-02T02:55:25.198953Z',
  notification_id: 'ntf_01hwvkmsknrgqw4z1598qw4ypt',
  data: {
    id: 'paymtd_01hs8zx6x377xfsfrt2bqsevbw',
    customer_id: 'ctm_01hv6y1jedq4p1n0yqn5ba3ky4',
    address_id: 'add_01hv8gq3318ktkfengj2r75gfx',
    type: 'card',
    origin: 'saved_during_purchase',
    saved_at: '2024-05-02T02:55:25.198953Z',
    updated_at: '2024-05-02T02:55:25.198953Z',
  },
};

export const PaymentMethodSavedMockExpectation = {
  data: {
    id: 'paymtd_01hs8zx6x377xfsfrt2bqsevbw',
    customerId: 'ctm_01hv6y1jedq4p1n0yqn5ba3ky4',
    addressId: 'add_01hv8gq3318ktkfengj2r75gfx',
    type: 'card',
    origin: 'saved_during_purchase',
    savedAt: '2024-05-02T02:55:25.198953Z',
    updatedAt: '2024-05-02T02:55:25.198953Z',
  },
  eventId: 'evt_01hwvkmsge7bhq1a31s35784zt',
  eventType: 'payment_method.saved',
  notificationId: 'ntf_01hwvkmsknrgqw4z1598qw4ypt',
  occurredAt: '2024-05-02T02:55:25.198953Z',
};
