/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IEventsResponse } from '../../../types';
import { IPriceNotificationResponse } from '../../../notifications';

export const PriceCreatedMock: IEventsResponse<IPriceNotificationResponse> = {
  event_id: 'evt_01h7zd9n8vch227m3dgwqcvf6t',
  event_type: 'price.created',
  occurred_at: '2023-08-16T14:51:48.380054Z',
  notification_id: 'ntf_01h7zd9nb2j92yhbfys5zam0gq',
  data: {
    id: 'pri_01h7zd9mzfq79850w4ryc39v38',
    status: 'active',
    type: 'standard',
    quantity: { maximum: 999, minimum: 1 },
    tax_mode: 'account_setting',
    product_id: 'pro_01h7zcgmdc6tmwtjehp3sh7azf',
    unit_price: { amount: '500', currency_code: 'USD' },
    custom_data: null,
    description: 'Monthly (per seat)',
    name: 'Monthly (per seat)',
    trial_period: { interval: 'day', frequency: 3 },
    billing_cycle: { interval: 'month', frequency: 1 },
    unit_price_overrides: [],
    import_meta: null,
  },
};

export const PriceCreatedMockExpectation = {
  data: {
    billingCycle: {
      frequency: 1,
      interval: 'month',
    },
    customData: null,
    description: 'Monthly (per seat)',
    id: 'pri_01h7zd9mzfq79850w4ryc39v38',
    importMeta: null,
    name: 'Monthly (per seat)',
    productId: 'pro_01h7zcgmdc6tmwtjehp3sh7azf',
    quantity: {
      maximum: 999,
      minimum: 1,
    },
    status: 'active',
    createdAt: null,
    updatedAt: null,
    taxMode: 'account_setting',
    trialPeriod: {
      frequency: 3,
      interval: 'day',
    },
    type: 'standard',
    unitPrice: {
      amount: '500',
      currencyCode: 'USD',
    },
    unitPriceOverrides: [],
  },
  eventId: 'evt_01h7zd9n8vch227m3dgwqcvf6t',
  eventType: 'price.created',
  notificationId: 'ntf_01h7zd9nb2j92yhbfys5zam0gq',
  occurredAt: '2023-08-16T14:51:48.380054Z',
};
