/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IEventsResponse, type IProductResponse } from '../../../types';

export const ProductImportedMock: IEventsResponse<IProductResponse> = {
  event_id: 'evt_01hgas2cm8r02nxryp83jqvg6k',
  event_type: 'product.imported',
  occurred_at: '2023-11-28T10:54:46.408439Z',
  notification_id: 'ntf_01hd46rqryfc8d7d5yz595k2k6',
  data: {
    id: 'pro_01h1vjes1y163xfj1rh1tkfb65',
    status: 'active',
    type: 'standard',
    name: 'Voice rooms addon',
    description:
      'Create voice rooms in your chats to work in real time alongside your colleagues. Includes unlimited voice rooms and recording backup for compliance.',
    tax_category: 'standard',
    image_url: 'https://paddle-sandbox.s3.amazonaws.com/user/10889/GcZzBjXRfiraensppgtQ_icon2.png',
    custom_data: null,
    created_at: '2023-06-01T13:30:50.302Z',
    import_meta: { external_id: '16a2c842-8ddc-11ee-b9d1-0242ac120002', imported_from: 'billing_platform' },
  },
};

export const ProductImportedMockExpectation = {
  data: {
    createdAt: '2023-06-01T13:30:50.302Z',
    customData: null,
    description:
      'Create voice rooms in your chats to work in real time alongside your colleagues. Includes unlimited voice rooms and recording backup for compliance.',
    id: 'pro_01h1vjes1y163xfj1rh1tkfb65',
    imageUrl: 'https://paddle-sandbox.s3.amazonaws.com/user/10889/GcZzBjXRfiraensppgtQ_icon2.png',
    importMeta: {
      externalId: '16a2c842-8ddc-11ee-b9d1-0242ac120002',
      importedFrom: 'billing_platform',
    },
    name: 'Voice rooms addon',
    status: 'active',
    taxCategory: 'standard',
    type: 'standard',
  },
  eventId: 'evt_01hgas2cm8r02nxryp83jqvg6k',
  eventType: 'product.imported',
  notificationId: 'ntf_01hd46rqryfc8d7d5yz595k2k6',
  occurredAt: '2023-11-28T10:54:46.408439Z',
};
