/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IEventsResponse, type IReportResponse } from '../../../types';

export const ReportCreatedMock: IEventsResponse<IReportResponse> = {
  event_id: 'evt_01hhq4c3nf0jrz7c46k4d8bc0x',
  event_type: 'report.created',
  occurred_at: '2023-12-15T16:18:54.255762Z',
  notification_id: 'ntf_01h8441jz6fr97hv7zemswj8cw',
  data: {
    id: 'rep_01hhq4c3b03g3x2kpkj8aecjv6',
    status: 'pending',
    rows: null,
    type: 'transactions',
    filters: [
      { name: 'updated_at', value: '2023-12-15', operator: 'lt' },
      { name: 'updated_at', value: '2023-11-16', operator: 'gte' },
      { name: 'collection_mode', value: ['manual'], operator: null },
    ],
    expires_at: null,
    created_at: '2023-12-15T16:18:53.92Z',
  },
};

export const ReportCreatedMockExpectation = {
  data: {
    createdAt: '2023-12-15T16:18:53.92Z',
    expiresAt: null,
    filters: [
      {
        name: 'updated_at',
        operator: 'lt',
        value: '2023-12-15',
      },
      {
        name: 'updated_at',
        operator: 'gte',
        value: '2023-11-16',
      },
      {
        name: 'collection_mode',
        operator: null,
        value: ['manual'],
      },
    ],
    id: 'rep_01hhq4c3b03g3x2kpkj8aecjv6',
    rows: null,
    status: 'pending',
    type: 'transactions',
  },
  eventId: 'evt_01hhq4c3nf0jrz7c46k4d8bc0x',
  eventType: 'report.created',
  notificationId: 'ntf_01h8441jz6fr97hv7zemswj8cw',
  occurredAt: '2023-12-15T16:18:54.255762Z',
};
