/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import type { SimulationScenarioType } from '../../../enums/index.js';
import type { IEventName } from '../../../notifications/index.js';

export interface CreateSimulation {
  notificationSettingId: string;
  type: IEventName | SimulationScenarioType;
  name: string;
  payload?: any;
}
