/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type SimulationStatus } from '../../../enums';

export interface ListSimulationQueryParameters {
  after?: string;
  notificationSettingId?: string[];
  orderBy?: string;
  perPage?: number;
  id?: string[];
  status?: SimulationStatus[];
}
