/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import type { SimulationScenarioType, SimulationStatus } from '../../../enums/index.js';
import type { IEventName } from '../../../notifications/index.js';

export interface UpdateSimulation {
  notificationSettingId?: string;
  name?: string;
  status?: SimulationStatus;
  type?: IEventName | SimulationScenarioType;
  payload?: any;
}
