/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */
import { IApiKeyNotificationResponse } from '../../types/index.js';
import { ApiKeyPermission, ApiKeyStatus } from '../../../enums/index.js';

export class ApiKeyNotification {
  public readonly id: string;
  public readonly name: string;
  public readonly description: string | null;
  public readonly key: string;
  public readonly status: ApiKeyStatus;
  public readonly permissions: ApiKeyPermission[];
  public readonly expiresAt: string | null;
  public readonly lastUsedAt: string | null;
  public readonly createdAt: string;
  public readonly updatedAt: string;

  constructor(apiKey: IApiKeyNotificationResponse) {
    this.id = apiKey.id;
    this.name = apiKey.name;
    this.description = apiKey.description ?? null;
    this.key = apiKey.key;
    this.status = apiKey.status;
    this.permissions = apiKey.permissions;
    this.expiresAt = apiKey.expires_at ?? null;
    this.lastUsedAt = apiKey.last_used_at ?? null;
    this.createdAt = apiKey.created_at;
    this.updatedAt = apiKey.updated_at;
  }
}
