/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type VerifyCheckoutDomainPaymentMethodRequestBody } from '../../../resources/index.js';
import { type ICheckoutDomainResponse } from '../../../types/index.js';
import { type Response, type ResponsePaginated } from '../../../internal/index.js';

export const CheckoutDomainMock: ICheckoutDomainResponse = {
  id: 'chedom_01j2abc3def4ghi5jkl6mno7pq',
  domain: 'app.example.com',
  status: 'verification_in_progress',
  payment_method_verification: {
    apple_pay: {
      status: 'verified',
    },
  },
  created_at: '2026-03-04T12:00:00.000Z',
  updated_at: '2026-03-04T14:30:00.000Z',
};

export const CheckoutDomainMockResponse: Response<ICheckoutDomainResponse> = {
  data: CheckoutDomainMock,
  meta: {
    request_id: '',
  },
};

export const ListCheckoutDomainsMockResponse: ResponsePaginated<ICheckoutDomainResponse> = {
  data: [CheckoutDomainMock],
  meta: {
    request_id: '',
    pagination: {
      estimated_total: 1,
      has_more: true,
      next: '/checkout-domains?after=1',
      per_page: 10,
    },
  },
};

export const VerifyCheckoutDomainPaymentMethodMock: VerifyCheckoutDomainPaymentMethodRequestBody = {
  paymentMethod: 'apple_pay',
};

export const VerifyCheckoutDomainPaymentMethodExpectation = {
  payment_method: 'apple_pay',
};
