/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { ErrorResponse } from '../../../internal/index.js';
import { responseProperty } from '../../../internal/types/response.js';

const tooManyRequestsResponseJson = {
  error: {
    type: 'request_error',
    code: 'too_many_requests',
    detail: 'IP address exceeded the allowed rate limit. Retry after the number of seconds in the Retry-After header.',
    documentation_url: 'https://developer.paddle.com/errors/shared/too_many_requests',
  },
  meta: {
    request_id: '',
  },
};

export const TooManyRequestsResponse: ErrorResponse = {
  ...tooManyRequestsResponseJson,
  [responseProperty]: new Response(JSON.stringify(tooManyRequestsResponseJson), {
    status: 429,
    statusText: 'Too Many Requests',
    headers: {
      'Content-Type': 'application/json',
      'Retry-After': '100',
    },
  }),
};
