/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { INotificationLogResponse, INotificationResponse, IReplayNotificationResponse } from '../../../types/index.js';
import { EventName } from '../../../notifications/index.js';
import { Response, ResponsePaginated } from '../../../internal/index.js';

export const NotificationMock: INotificationResponse = {
  id: 'ntf_01ghbkd0frb9k95cnhwd1bxpvk',
  type: 'address.updated',
  status: 'not_attempted',
  payload: {
    event_id: 'evt_01gks14ge726w50ch2tmaw2a1x',
    event_type: EventName.AddressUpdated,
    occurred_at: '2024-10-12T07:20:50.52Z',
    data: {
      country_code: 'AD',
      created_at: '',
      id: '',
      status: 'active',
      updated_at: '',
    },
    notification_id: 'ntf_01ghbkd0frb9k95cnhwd1bxpvk',
  },
  occurred_at: '2024-10-12T07:20:50.52Z',
  delivered_at: '2024-10-12T07:20:50.52Z',
  replayed_at: '2024-10-12T07:20:50.52Z',
  origin: 'event',
  last_attempt_at: '2024-10-12T07:20:50.52Z',
  retry_at: '2024-10-12T07:20:50.52Z',
  times_attempted: 10,
  notification_setting_id: 'ntfset_01gt21c5pdx9q1e4mh1xrsjjn6',
};

export const NotificationReplayMockResponse: Response<IReplayNotificationResponse> = {
  data: {
    notification_id: 'ntf_1234',
  },
  meta: {
    request_id: '',
  },
};

export const NotificationMockResponse: Response<INotificationResponse> = {
  data: NotificationMock,
  meta: {
    request_id: '',
  },
};

export const NotificationLogMockResponse: INotificationLogResponse[] = [
  {
    id: 'ntflog_01h8c0bswct46cwamynrzs6fwr',
    response_code: 200,
    response_content_type: 'text/plain; charset=UTF-8',
    response_body: '',
    attempted_at: '2023-08-21T12:15:54.764232Z',
  },
  {
    id: 'ntflog_01h8c04xjj1ybcgsawp54h5zkr',
    response_code: 404,
    response_content_type: 'application/json',
    response_body: '{"success":false,"error":{"message":"Token not found","id":null}}',
    attempted_at: '2023-08-21T12:12:09.170559Z',
  },
  {
    id: 'ntflog_01h8bzyx2g57ywng4edfnpycya',
    response_code: 404,
    response_content_type: 'application/json',
    response_body: '{"success":false,"error":{"message":"Token not found","id":null}}',
    attempted_at: '2023-08-21T12:08:52.049462Z',
  },
];

export const ListNotificationMockResponse: ResponsePaginated<INotificationResponse> = {
  data: [NotificationMock],
  meta: {
    request_id: '',
    pagination: {
      estimated_total: 10,
      has_more: true,
      next: '/notifications?after=1',
      per_page: 10,
    },
  },
};

export const ListNotificationLogsMockResponse: ResponsePaginated<INotificationLogResponse> = {
  data: NotificationLogMockResponse,
  meta: {
    request_id: '',
    pagination: {
      estimated_total: 10,
      has_more: true,
      next: '/notifications/ntf_1234/logs?after=1',
      per_page: 10,
    },
  },
};
