/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IReportCsvResponse, IReportResponse } from '../../../types';
import { Response, ResponsePaginated } from '../../../internal';

export const ReportMock: IReportResponse = {
  id: 'add_01gm302t81w94gyjpjpqypkzkf',
  status: 'pending',
  rows: 10,
  type: 'transactions',
  filters: [{ name: 'updated_at', operator: 'lt', value: '2024-10-13T07:20:50.52Z' }],
  expires_at: '2019-10-12T07:20:50.52Z',
  created_at: '2024-10-12T07:20:50.52Z',
};

export const ReportCsvMock: IReportCsvResponse = {
  url: 'https://localhost',
};

export const ReportMockResponse: Response<IReportResponse> = {
  data: ReportMock,
  meta: {
    request_id: '',
  },
};

export const ReportCsvMockResponse: Response<IReportCsvResponse> = {
  data: ReportCsvMock,
  meta: {
    request_id: '',
  },
};

export const ListReportMockResponse: ResponsePaginated<IReportResponse> = {
  data: [ReportMock],
  meta: {
    request_id: '',
    pagination: {
      estimated_total: 10,
      has_more: true,
      next: '/reports?after=1',
      per_page: 10,
    },
  },
};
