/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { ISimulationResponse } from '../../../types/index.js';
import { Response, ResponsePaginated } from '../../../internal/index.js';
import { CreateSimulationRequestBody, UpdateSimulationRequestBody } from '../../../resources/index.js';

export const CreateSimulationMock: CreateSimulationRequestBody = {
  notificationSettingId: 'ntfset_01gt21c5pdx9q1e4mh1xrsjjn6',
  type: 'address.created',
  name: 'New address created',
};

export const updateSimulationMock: UpdateSimulationRequestBody = {
  name: 'New UK address created',
};

export const SimulationMock: ISimulationResponse = {
  id: 'ntfsim_01ghbkd0frb9k95cnhwd1bxpvk',
  status: 'active',
  notification_setting_id: 'ntfset_01gt21c5pdx9q1e4mh1xrsjjn6',
  name: 'New address created',
  type: 'address.created',
  payload: null,
  last_run_at: '2024-10-12T07:20:50.52Z',
  created_at: '2024-10-12T07:20:50.52Z',
  updated_at: '2024-10-13T07:20:50.52Z',
  config: null,
};

export const SimulationMockResponse: Response<ISimulationResponse> = {
  data: SimulationMock,
  meta: {
    request_id: '',
  },
};

export const ListSimulationMockResponse: ResponsePaginated<ISimulationResponse> = {
  data: [SimulationMock],
  meta: {
    request_id: '',
    pagination: {
      estimated_total: 10,
      has_more: true,
      next: '/simulations?after=1',
      per_page: 10,
    },
  },
};

export const CreateSimulationScenarioMock: CreateSimulationRequestBody = {
  notificationSettingId: 'ntfset_123',
  type: 'subscription_creation',
  name: 'New subscription created',
  config: {
    subscriptionCreation: {
      entities: {
        customerId: 'ctm_123',
      },
      options: {
        customerSimulatedAs: 'existing_email_matched',
      },
    },
  },
};

export const SimulationScenarioMock: ISimulationResponse = {
  id: 'ntfsim_123',
  status: 'active',
  notification_setting_id: 'ntfset_123',
  name: 'New subscription created',
  type: 'subscription_creation',
  payload: null,
  last_run_at: null,
  created_at: '2025-04-08T14:32:18.193033Z',
  updated_at: '2025-04-08T14:32:18.193033Z',
  config: {
    subscription_cancellation: null,
    subscription_creation: {
      entities: {
        customer_id: 'ctm_01j91fa47z7fx1zayjvntk0yps',
        address_id: null,
        business_id: null,
        payment_method_id: null,
        discount_id: null,
        transaction_id: null,
        items: null,
      },
      options: {
        customer_simulated_as: 'existing_email_matched',
        business_simulated_as: 'not_provided',
        discount_simulated_as: 'not_provided',
      },
    },
    subscription_pause: null,
    subscription_renewal: null,
    subscription_resume: null,
  },
};

export const CreateSimulationScenarioMockResponse: Response<ISimulationResponse> = {
  data: SimulationScenarioMock,
  meta: {
    request_id: '',
  },
};
