/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CountryCode } from '../../enums';
import { type IAddressPreviewResponse } from '../../resources';

export class AddressPreview {
  public readonly postalCode: string | null;
  public readonly countryCode: CountryCode;

  constructor(address: IAddressPreviewResponse) {
    this.postalCode = address.postal_code ? address.postal_code : null;
    this.countryCode = address.country_code;
  }
}
