/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITransactionResponse } from '../../types';
import { Collection } from '../../internal/base';
import { Transaction } from './transaction';

export class TransactionCollection extends Collection<ITransactionResponse, Transaction> {
  override fromJson(data: ITransactionResponse): Transaction {
    return new Transaction(data);
  }
}
