/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITransactionLineItemResponse } from '../../types';
import { TransactionProration, UnitTotals, Totals, Product } from '../index';

export class TransactionLineItem {
  public readonly id: string;
  public readonly priceId: string;
  public readonly quantity: number;
  public readonly proration: TransactionProration | null;
  public readonly taxRate: string;
  public readonly unitTotals: UnitTotals | null;
  public readonly totals: Totals | null;
  public readonly product: Product | null;

  constructor(transactionLineItem: ITransactionLineItemResponse) {
    this.id = transactionLineItem.id;
    this.priceId = transactionLineItem.price_id;
    this.quantity = transactionLineItem.quantity;
    this.proration = transactionLineItem.proration ? new TransactionProration(transactionLineItem.proration) : null;
    this.taxRate = transactionLineItem.tax_rate;
    this.unitTotals = transactionLineItem.unit_totals ? new UnitTotals(transactionLineItem.unit_totals) : null;
    this.totals = transactionLineItem.totals ? new Totals(transactionLineItem.totals) : null;
    this.product = transactionLineItem.product ? new Product(transactionLineItem.product) : null;
  }
}
