/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type ITransactionInvoicePDF } from '../../types/index.js';

export class TransactionInvoicePDF {
  public readonly url: string;

  constructor(transaction: ITransactionInvoicePDF) {
    this.url = transaction.url;
  }
}
