/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */
import { Status } from '../../../enums/index.js';
import { ImportMetaNotification } from '../shared/index.js';
import { IDiscountGroupNotificationResponse } from '../../types/index.js';

export class DiscountGroupNotification {
  public readonly id: string;
  public readonly name: string;
  public readonly status: Status;
  public readonly createdAt: string;
  public readonly updatedAt: string;
  public readonly importMeta: ImportMetaNotification | null;

  constructor(discountGroupResponse: IDiscountGroupNotificationResponse) {
    this.id = discountGroupResponse.id;
    this.name = discountGroupResponse.name;
    this.status = discountGroupResponse.status;
    this.createdAt = discountGroupResponse.created_at;
    this.updatedAt = discountGroupResponse.updated_at;
    this.importMeta = discountGroupResponse.import_meta
      ? new ImportMetaNotification(discountGroupResponse.import_meta)
      : null;
  }
}
