/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CurrencyCode } from '../../enums/index.js';
import { type IMetricsTimeseriesMonthlyRecurringRevenueChangeResponse } from '../../types/index.js';
import { MetricsTimeseriesMonthlyRecurringRevenueDatapoint } from './metrics-timeseries-monthly-recurring-revenue-datapoint.js';

export class MetricsTimeseriesMonthlyRecurringRevenueChange {
  public readonly currencyCode: CurrencyCode;
  public readonly endsAt: string;
  public readonly interval: 'day';
  public readonly startsAt: string;
  public readonly timeseries: MetricsTimeseriesMonthlyRecurringRevenueDatapoint[];
  public readonly updatedAt: string;

  constructor(data: IMetricsTimeseriesMonthlyRecurringRevenueChangeResponse) {
    this.currencyCode = data.currency_code;
    this.endsAt = data.ends_at;
    this.interval = data.interval;
    this.startsAt = data.starts_at;
    this.timeseries = data.timeseries.map(
      (datapoint) => new MetricsTimeseriesMonthlyRecurringRevenueDatapoint(datapoint),
    );
    this.updatedAt = data.updated_at;
  }
}
