/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CurrencyCode } from '../../enums/index.js';
import { type IMetricsTimeseriesRefundsResponse } from '../../types/index.js';
import { MetricsTimeseriesRefundsDatapoint } from './metrics-timeseries-refunds-datapoint.js';

export class MetricsTimeseriesRefunds {
  public readonly currencyCode: CurrencyCode;
  public readonly endsAt: string;
  public readonly interval: 'day';
  public readonly startsAt: string;
  public readonly timeseries: MetricsTimeseriesRefundsDatapoint[];
  public readonly updatedAt: string;

  constructor(data: IMetricsTimeseriesRefundsResponse) {
    this.currencyCode = data.currency_code;
    this.endsAt = data.ends_at;
    this.interval = data.interval;
    this.startsAt = data.starts_at;
    this.timeseries = data.timeseries.map((datapoint) => new MetricsTimeseriesRefundsDatapoint(datapoint));
    this.updatedAt = data.updated_at;
  }
}
