/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMetricsTimeseriesActiveSubscribersDatapoint } from '../../types/index.js';

export class MetricsTimeseriesActiveSubscribersDatapoint {
  public readonly count: number;
  public readonly timestamp: string;

  constructor(datapoint: IMetricsTimeseriesActiveSubscribersDatapoint) {
    this.count = datapoint.count;
    this.timestamp = datapoint.timestamp;
  }
}
