/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMetricsTimeseriesChargebacksDatapoint } from '../../types/index.js';

export class MetricsTimeseriesChargebacksDatapoint {
  public readonly count: number;
  public readonly timestamp: string;

  constructor(datapoint: IMetricsTimeseriesChargebacksDatapoint) {
    this.count = datapoint.count;
    this.timestamp = datapoint.timestamp;
  }
}
