/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMetricsTimeseriesCheckoutConversionDatapoint } from '../../types/index.js';

export class MetricsTimeseriesCheckoutConversionDatapoint {
  public readonly completedCount: number;
  public readonly count: number;
  public readonly rate: string;
  public readonly timestamp: string;

  constructor(datapoint: IMetricsTimeseriesCheckoutConversionDatapoint) {
    this.completedCount = datapoint.completed_count;
    this.count = datapoint.count;
    this.rate = datapoint.rate;
    this.timestamp = datapoint.timestamp;
  }
}
