/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type CurrencyCode, type MetricsTimeseriesInterval } from '../../enums/index.js';
import { type IMetricsTimeseriesRevenueResponse } from '../../types/index.js';
import { MetricsTimeseriesRevenueDatapoint } from './metrics-timeseries-revenue-datapoint.js';

export class MetricsTimeseriesRevenue {
  public readonly currencyCode: CurrencyCode;
  public readonly endsAt: string;
  public readonly interval: MetricsTimeseriesInterval;
  public readonly startsAt: string;
  public readonly timeseries: MetricsTimeseriesRevenueDatapoint[];
  public readonly updatedAt: string;

  constructor(data: IMetricsTimeseriesRevenueResponse) {
    this.currencyCode = data.currency_code;
    this.endsAt = data.ends_at;
    this.interval = data.interval;
    this.startsAt = data.starts_at;
    this.timeseries = data.timeseries.map((datapoint) => new MetricsTimeseriesRevenueDatapoint(datapoint));
    this.updatedAt = data.updated_at;
  }
}
