/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMetricsTimeseriesRevenueDatapoint } from '../../types/index.js';

export class MetricsTimeseriesRevenueDatapoint {
  public readonly amount: string;
  public readonly count: number;
  public readonly timestamp: string;

  constructor(datapoint: IMetricsTimeseriesRevenueDatapoint) {
    this.amount = datapoint.amount;
    this.count = datapoint.count;
    this.timestamp = datapoint.timestamp;
  }
}
