/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMetricsTimeseriesActiveSubscribersResponse } from '../../types/index.js';
import { MetricsTimeseriesActiveSubscribersDatapoint } from './metrics-timeseries-active-subscribers-datapoint.js';

export class MetricsTimeseriesActiveSubscribers {
  public readonly endsAt: string;
  public readonly interval: 'day';
  public readonly startsAt: string;
  public readonly timeseries: MetricsTimeseriesActiveSubscribersDatapoint[];
  public readonly updatedAt: string;

  constructor(data: IMetricsTimeseriesActiveSubscribersResponse) {
    this.endsAt = data.ends_at;
    this.interval = data.interval;
    this.startsAt = data.starts_at;
    this.timeseries = data.timeseries.map(
      (datapoint) => new MetricsTimeseriesActiveSubscribersDatapoint(datapoint),
    );
    this.updatedAt = data.updated_at;
  }
}
