/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IMetricsTimeseriesMonthlyRecurringRevenueDatapoint } from '../../types/index.js';

export class MetricsTimeseriesMonthlyRecurringRevenueDatapoint {
  public readonly amount: string;
  public readonly timestamp: string;

  constructor(datapoint: IMetricsTimeseriesMonthlyRecurringRevenueDatapoint) {
    this.amount = datapoint.amount;
    this.timestamp = datapoint.timestamp;
  }
}
