name: Publish to Beta Tag

on:
  push:
    branches:
      - release/beta

jobs:
  run-publish:
    name: Run publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test

      - name: Publish
        run: bun run publish:beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
