/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Collection } from '../../internal/base/index.js';
import { type ICheckoutDomainResponse } from '../../types/index.js';
import { CheckoutDomain } from './checkout-domain.js';

export class CheckoutDomainCollection extends Collection<ICheckoutDomainResponse, CheckoutDomain> {
  override fromJson(data: ICheckoutDomainResponse): CheckoutDomain {
    return new CheckoutDomain(data);
  }
}
