/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { type IPayPalResponse } from '../../types';

export class PayPal {
  public readonly email: string;
  public readonly reference: string;

  constructor(payPalResponse: IPayPalResponse) {
      this.email = payPalResponse.email;
      this.reference = payPalResponse.reference;
  }
}
