/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import type { SavedPaymentMethodType, SavedPaymentOrigin } from '../../enums';
import type { IPaymentMethodResponse } from '../../types';
import { PaymentCard, PayPal } from '../shared';

export class PaymentMethod {
  public readonly id: string;
  public readonly customerId: string;
  public readonly addressId: string;
  public readonly type: SavedPaymentMethodType;
  public readonly card: PaymentCard | null;
  public readonly paypal: PayPal | null;
  public readonly origin: SavedPaymentOrigin;
  public readonly savedAt: string;
  public readonly updatedAt: string;

  constructor(paymentMethodResponse: IPaymentMethodResponse) {
    this.id = paymentMethodResponse.id;
    this.customerId = paymentMethodResponse.customer_id;
    this.addressId = paymentMethodResponse.address_id;
    this.type = paymentMethodResponse.type;
    this.card = paymentMethodResponse.card ? new PaymentCard(paymentMethodResponse.card) : null;
    this.paypal = paymentMethodResponse.paypal ? new PayPal(paymentMethodResponse.paypal) : null;
    this.origin = paymentMethodResponse.origin;
    this.savedAt = paymentMethodResponse.saved_at;
    this.updatedAt = paymentMethodResponse.updated_at;
  }
}
