/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { PaymentMethod } from '../../entities/index.js';
import { type IPaymentMethodResponse } from '../../types/index.js';
import { Collection } from '../../internal/base/index.js';

export class PaymentMethodCollection extends Collection<IPaymentMethodResponse, PaymentMethod> {
  override fromJson(data: IPaymentMethodResponse): PaymentMethod {
    return new PaymentMethod(data);
  }
}
