/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event';
import { type IEventsResponse } from '../../../types';
import { EventName } from '../../helpers';
import { AddressNotification } from '../../entities';
import { type IAddressNotificationResponse } from '../../types';

export class AddressUpdatedEvent extends Event {
  public override readonly eventType = EventName.AddressUpdated;
  public override readonly data: AddressNotification;

  constructor(response: IEventsResponse<IAddressNotificationResponse>) {
    super(response);
    this.data = new AddressNotification(response.data);
  }
}
