/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { Event } from '../../../entities/events/event.js';
import { EventName } from '../../helpers/index.js';
import { AddressNotification } from '../../entities/index.js';
import { type IEventsResponse } from '../../../types/index.js';
import { type IAddressNotificationResponse } from '../../types/index.js';

export class AddressUpdatedEvent extends Event {
  public override readonly eventType = EventName.AddressUpdated;
  public override readonly data: AddressNotification;

  constructor(response: IEventsResponse<IAddressNotificationResponse>) {
    super(response);
    this.data = new AddressNotification(response.data);
  }
}
