/**
 *  ! Autogenerated code !
 *  Do not make changes to this file.
 *  Changes may be overwritten as part of auto-generation.
 */

import { BaseResource, PathParameters, QueryParameters } from '../../internal/base/index.js';
import { type ErrorResponse, type Response } from '../../internal/index.js';
import { CheckoutDomain, CheckoutDomainCollection } from '../../entities/index.js';
import { type ICheckoutDomainResponse } from '../../types/index.js';
import {
  type ListCheckoutDomainsQueryParameters,
  type VerifyCheckoutDomainPaymentMethodRequestBody,
} from './operations/index.js';

const CheckoutDomainPaths = {
  list: '/checkout-domains',
  get: '/checkout-domains/{domain_id}',
  delete: '/checkout-domains/{domain_id}',
  verifyPaymentMethod: '/checkout-domains/{domain_id}/verify-payment-method',
} as const;

export * from './operations/index.js';

export class CheckoutDomainsResource extends BaseResource {
  public list(queryParams?: ListCheckoutDomainsQueryParameters): CheckoutDomainCollection {
    const queryParameters = new QueryParameters(queryParams);
    return new CheckoutDomainCollection(this.client, CheckoutDomainPaths.list + queryParameters.toQueryString());
  }

  public async get(domainId: string): Promise<CheckoutDomain> {
    const urlWithPathParams = new PathParameters(CheckoutDomainPaths.get, {
      domain_id: domainId,
    }).deriveUrl();

    const response = await this.client.get<undefined, Response<ICheckoutDomainResponse> | ErrorResponse>(
      urlWithPathParams,
    );

    const data = this.handleResponse<ICheckoutDomainResponse>(response);

    return new CheckoutDomain(data);
  }

  public async delete(domainId: string): Promise<undefined> {
    const urlWithPathParams = new PathParameters(CheckoutDomainPaths.delete, {
      domain_id: domainId,
    }).deriveUrl();

    const response = await this.client.delete(urlWithPathParams);

    if (response) {
      this.handleResponse<undefined>(response);
    }
  }

  public async verifyPaymentMethod(
    domainId: string,
    requestBody: VerifyCheckoutDomainPaymentMethodRequestBody,
  ): Promise<CheckoutDomain> {
    const urlWithPathParams = new PathParameters(CheckoutDomainPaths.verifyPaymentMethod, {
      domain_id: domainId,
    }).deriveUrl();

    const response = await this.client.post<
      VerifyCheckoutDomainPaymentMethodRequestBody,
      Response<ICheckoutDomainResponse> | ErrorResponse
    >(urlWithPathParams, requestBody);

    const data = this.handleResponse<ICheckoutDomainResponse>(response);

    return new CheckoutDomain(data);
  }
}
